### ISSUE TITLE
Expose 'unreadCardCountForCategories' to RN

### ISSUE THREAD

**Issue by brianjd** [Appboy/appboy-react-sdk#1]

**Comment by briancaw** [comment]
Hi @brianjd 

Thanks for this feedback.  We'll aim to incorporate this in our next release which we're aiming to be in the next 6 weeks.

Please let us know if you have any further comments/questions.

Thanks,
Brian

**Comment by tiffanylu** [comment]
Hi @brianjd,

We just released v1.0.0, which exposes `ReactAppboy.getUnreadCardCountForCategories()` and `ReactAppboy.getCardCountForCategories()`. Thanks again for raising this up!

Best,
Tiff
