### ISSUE TITLE
Update to latest native iOS bridge (3.31.2)

### ISSUE THREAD

**Issue by lucas-mancini** [Appboy/appboy-react-sdk#100]
Are there any plans to update the underlying native iOS bridge?

I am using this dependency and I am currently interested in using upgrading to [Braze iOS SDK 3.31.2](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3312) which has some fixes related to SDK localizations.

**Comment by wesleyorbin** [comment]
Hi @lucas-mancini! Thanks for reaching out. We should be able to get this released soon. I'll update you here when we do.

**Comment by wesleyorbin** [comment]
@lucas-mancini We just released v1.26.0, which upgrades the native iOS bridge to 3.31.2. Please reach out if you have any issues. Thank you!
