### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by dmsierra11** [Appboy/appboy-react-sdk#101]
I followed the documentation step by step but after adding the `react-native-appboy-sdk`to the `:app/build.gradle` and tying to compile it throws the following errors:

`Unable to resolve dependency for ':app@debug/compileClasspath': Resolved 'androidx.webkit:webkit:1.3.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debug/compileClasspath': Resolved 'com.appboy:android-sdk-ui:12.0.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debug/compileClasspath': Resolved 'com.appboy:android-sdk-base:12.0.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Resolved 'com.appboy:android-sdk-base:12.0.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Resolved 'com.appboy:android-sdk-ui:12.0.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Resolved 'androidx.webkit:webkit:1.3.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Resolved 'com.appboy:android-sdk-ui:12.0.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Resolved 'androidx.webkit:webkit:1.3.0' which is not part of the dependency lock state
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Resolved 'com.appboy:android-sdk-base:12.0.0' which is not part of the dependency lock state
`

**Comment by radixdev** [comment]
Are you using "react-native link"?

**Comment by dmsierra11** [comment]
No, I am following the 'Without react-native link' steps. My app is on react native `0.63.3` and is my understanding that `react-native link` is not needed anymore after `0.60`

**Comment by dmsierra11** [comment]
> Are you using "react-native link"?

No, I am following the 'Without react-native link' steps. My app is on react native 0.63.3 and is my understanding that react-native link is not needed anymore after 0.60

**Comment by dmsierra11** [comment]
It turns out it wasn't an issue with this library. It was due to the gradle configuration in my project, which includes [locking dependency versions](https://docs.gradle.org/current/userguide/dependency_locking.html). Executing `./gradlew resolveAndLockAll --write-locks` to update lock files solves de issue.
