### ISSUE TITLE
Promise for requestContentCardsRefresh

### ISSUE THREAD

**Issue by drop-evan** [Appboy/appboy-react-sdk#111]
Hi, is it possible for `requestContentCardsRefresh` to return a promise, so I can wait until its done before calling `getContentCards`? If I call `getContentCards` immediately after `requestContentCardsRefresh` I get the old content cards and need to refresh a second time to get the new ones.

**Comment by wesleyorbin** [comment]
Hi @drop-evan! Thanks for reaching out. You should be able to use `addListener` to subscribe to updates to content cards. It will invoked when your refresh request is completed and you can call `getContentCards` in your subscriber to get the newest cards. You can see an example of how to use it in the [sample project](https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L89). Please let me know if this solves your issue.

**Comment by drop-evan** [comment]
Thank you! That seems to work

**Comment by lloisp** [comment]
Hi! Docs mention `Braze.getContentCards()` "will return the latest list of cards from the server", presumably without having to run `requestContentCardsRefresh`. However, same as OP, I am not getting the latest cards until I refresh.

Are the docs incorrect?

**Comment by hokstuff** [comment]
Hi @lloisp,

In [version 3.0.0](https://github.com/braze-inc/braze-react-native-sdk/blob/master/CHANGELOG.md#changed), the implementation of `getContentCards()` performs a refresh and returns a promise of an array of Content Cards on both [iOS](https://github.com/braze-inc/braze-react-native-sdk/blob/98b3df82bdbef7db17f23ab3965bdf41096e776c/iOS/BrazeReactBridge/BrazeReactBridge/BrazeReactBridge.m#L539) and [Android](https://github.com/braze-inc/braze-react-native-sdk/blob/f739ed0dd83965a7bb05f97339f8a3b7781bee6f/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt#L380). Prior to this change, iOS did not make a refresh - so the current docs in the related PR are accurate, and the code comments in the JS layer of the SDK will be updated in the next release.

Thanks!
