### ISSUE TITLE
Crash App if there "type" with array value in eventProperties

### ISSUE THREAD

**Issue by moonjava2005** [Appboy/appboy-react-sdk#112]
App will be crashed if we send data like this

`appboy.logCustomEvent(SOME_EVENT_NAME, {type:['a','b']})`

**Comment by siempre** [comment]
👍

**Comment by lowip** [comment]
Hi @moonjava2005,

Thank you for the report.
This feature is now available in our latest release (see [changelog entry](https://github.com/Appboy/appboy-react-sdk/blob/master/CHANGELOG.md#1330)).
