### ISSUE TITLE
changeUser got 1 arguments, expected 2 (Android, v1.29.0)

### ISSUE THREAD

**Issue by jarredt** [Appboy/appboy-react-sdk#115]
Platform: Android
Lib version: 1.29.0

When I call `changeUser` with an id on Android, I get the error below. iOS is working fine. I do not get this error on v1.28.0.

![Screen Shot 2021-06-03 at 11 19 37 AM](https://user-images.githubusercontent.com/16692671/120693517-f4067a80-c45d-11eb-8c7e-3f34c84b202c.png)

**Comment by jarredt** [comment]
I believe this is because there are two `changeUser` methods defined in the bridge file now: https://github.com/Appboy/appboy-react-sdk/blob/1.29.0/android/src/main/java/com/appboy/reactbridge/AppboyReactBridge.java#L113-L121

**Comment by lowip** [comment]
Hi @jarredt,

Thank you for reporting this issue, we are aware of it and are working on a fix to be released soon.

**Comment by wesleyorbin** [comment]
Hi @jarredt. We just released 1.29.1, which fixes this issue.

**Comment by Bucimis** [comment]
Hi @jarredt, just a heads up that we have a crashing iOS Content Cards regression in 1.29.0 (native 4.2.0). If you are not using our out-of-the-box Content Cards UI, you won't be affected, but otherwise please stand by for a patch release coming in the next few days.

**Comment by lguardado** [comment]
I'm having this issue since v 1.29.1... any ideas?

**Comment by wesleyorbin** [comment]
Hi @lguardado! At this time, we'd recommend staying on 1.28.0 or below until we release the fix mentioned above. As for why you're still seeing the issue in 1.29.1, `yarn` can sometimes aggressively cache older versions. If you check the SDK in your `node_modules`, do you see 1.29.1 or 1.29.0?

**Comment by lguardado** [comment]
Hi @wesleyorbin, thank you so much for the quick reply!
In my `node_modules` I see `1.29.1`. 
I'll stay in `1.28.0` then and take a look at this issue to know when it's fixed!

Thanks again.
Lucas

**Comment by wesleyorbin** [comment]
We just released 1.30.0, which updates the iOS native SDK to 4.3.0 and fixes the Content Cards crash issue.

@lguardado Can you see if updating to this version fixes your issue with `changeUser`?
