### ISSUE TITLE
[Feature Request] Add support for Expo Config Plugins

### ISSUE THREAD

**Issue by leggomuhgreggo** [Appboy/appboy-react-sdk#119]
I'm on a team that's fixin to start work on a cross-platform Expo app, intended to replace our three legacy clients. Wanted to inquire whether y'all would consider adding support for [Config Plugins](https://docs.expo.io/guides/config-plugins/), so this library can be used with the Expo Managed Workflow (i.e. without ejecting)

This would enable Expo users to use the Braze/appboy SDK with much less friction

Thanks for your consideration!

## Feature Context

Over the past several months Expo has introduced features which enable apps to use external native modules, without ejecting Expo's managed workflow. 

The customizations to the iOS and Android code that are required by a given native module are automated, using an AST-based API that Expo provides through  "Config Plugins" feature.

These automations (called "mods") are executed during a new "Prebuild" phase, in which boilerplate ios and android directories are created — and then their respective files are altered, based on the instructions in a given modules config plugin. The end result is essentially the same as if you ejected and manually changed the ios/android files. 

Here's the [Expo blog post](https://blog.expo.io/introducing-expo-run-commands-835ae8da4813) announcing Config Plugins and the associated feature-set.

## Overview of Proposed Implementation

The process for creating a Config Plugin is detailed here:
https://docs.expo.io/guides/config-plugins/#creating-a-plugin

There are a few different "recipes" for how to implement — but the gist of it is:

- Create the `app.plugin.js` file, at the project root — which serves as a standard entrypoint where expo can resolve the plugin code. [ex: [`expo-camera`](https://github.com/expo/expo/blob/master/packages/expo-camera/app.plugin.js)]
- Export a function prefixed using "with" (eg `withFeature`) which accepts a `config` object that can be used, along with `@expo/config-plugins` methods, to implement mods for each platform's native code. [ex: [`withCamera`](https://github.com/expo/expo/blob/master/packages/expo-camera/plugin/src/withCamera.ts)]
- Add mods corresponding to the setup steps in your README.md
- Celebrate!

**Comment by nathankleyn** [comment]
Huge plus one from us here at [Portify](https://github.com/Portify)! This would massively simplify the integration effort for us with Braze. 👍

**Comment by wesleyorbin** [comment]
Hi everyone! It's on our roadmap to do a deep dive into supporting this. We will keep you updated here. Thank you for your patience!

**Comment by fantasyado** [comment]
> We just upgraded to Expo 43 and are experiencing issues with our previously working config plugin for Braze. Posting here to see if anyone else was experiencing anything similar.

@wesleyorbin Hello, Have you fixed the problem with Expo 43?  I'm also trying to integrate with braze in the Expo project without ejecting.  Do you mind sharing your plugin code? I haven't dealt with expo plugin before...

Thanks very much!

**Comment by Bucimis** [comment]
Hi @fantasyado, we still don't offer formal non-ejected Expo support but it's still on our roadmap (likely target is first half next year). Are you running into issues with a config plugin for Expo 43 specifically, or just looking at how to get started?

**Comment by fantasyado** [comment]
Hi @Bucimis  I'm looking at how to get started.  our project has developed many features on top of Expo, so unless there's no other option we really don't want to eject...  Do you think the config-plugin way is doable?  Will it be very complicated?
Any information is appreciated.

**Comment by wesleyorbin** [comment]
@fantasyado I would follow along with the [Expo docs](https://docs.expo.dev/guides/config-plugins/) and try it out. Based on what I'm seeing, it may be possible, but you'd likely have to use a mod to edit the `AppDelegate` for iOS and `MainApplication` for Android.

**Comment by iboxgithub** [comment]
Hi, I am following this [tutorial](https://instamobile.io/mobile-development/react-native-music-player/) to try to make your lib work with an Expo Bare workflow (ejected) but I have few open points:

- it works on iOS and Android but is their implementation correct?
- don't know why they use the variable `isCurrentTrack`
- [android warning] No task registered for key TrackPlayer
- it crashes on Web cf [this issue](https://github.com/expo/expo/issues/16227#issuecomment-1032968514) (Can't resolve '../Utilities/Platform'), mentioned [here](https://stackoverflow.com/questions/60746444/utilities-platform-missing-for-react-native) but couldn't find a fix for me

anyone else with these issues?

**Comment by wesleyorbin** [comment]
Hi @iboxgithub. I believe you may have meant to post this in another repo (maybe https://github.com/DoubleSymmetry/react-native-track-player?).

**Comment by EvanBacon** [comment]
@westhechiang if you have any feedback on Expo Config Plugins, I'd love to hear it! You can message me directly on Twitter [@baconbrix](https://twitter.com/Baconbrix) or on Discord `Bacon#8417`.

I've run the feature request by the team to see if anyone on our side has availability.

**Comment by giautm** [comment]
Hi everyone 👋 , I'm going to help create an Expo plug-in for `appboy-react-sdk`. However, after I read the documentation, I noticed that some parts of the SDK need you to install with the native code. So if you need this feature asks the Bazel team for support.

https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/inapp_messages/#accessing-in-app-message-data

**Comment by EvanBacon** [comment]
The Braze team has asked that this feature be handled in-house and that existing customers reach out to them directly for support (vikhash.charadva@braze.com), so we must unfortunately stop working on this feature.

**Comment by davidbielik** [comment]
Hi @giautm and @EvanBacon thanks for your interest and willingness to contribute to a React Native/Expo integration. 

I'll email you tomorrow to learn more about collaborating on this feature.

**Comment by raffiot** [comment]
Hi ! We are also going to use it at [Cajoo](https://www.cajoo.eu/), what is the current status of this track ?
Thank you very much.

**Comment by farkmarnum** [comment]
Hi all! At [Nayya](https://www.nayya.com/), we also use Braze + Expo managed workflow, and we've been blocked from using Braze in our React Native app due to the lack of a config plugin.

In order to un-block, we've written a [Expo config plugin for Braze](https://github.com/Nayya-com/braze-expo-plugin). This plugin is likely not generalized enough to meet the needs of all Braze customers, and it could also certainly use some improvements from subject matter experts at Braze and Expo.

A few shortcomings of note:
- It has only been tested with Expo SDK v44.0.0.
- It has not been thoroughly tested yet.
- It assumes you are using `eas build` with EAS managed credentials, and has not been tested for other configurations.
- It uses a fair amount of "dangerous" mods that use regex and string manipulation, as opposed to safer methods that do not do this. This means that the approach can likely be improved a lot and made to be less brittle, but we'll leave that for the Expo experts 😅 -- it was difficult to find "safe" ways to modify most of these files.
- It does not support all Braze customization options (see the listed [TODOs](https://github.com/Nayya-com/braze-expo-plugin#todo)).

That being said, we're sharing it as it may be a helpful starting place for other teams looking to write a config plugin until the Braze+Expo teams are able to release one for all customers. And it may be a helpful point of reference for you @davidbielik & @EvanBacon. Happy to chat through the approach and answer any questions.

**Comment by davidbielik** [comment]
Hi everyone, 

Thanks for your patience on this feature request. I want to provide an update on our plans and timelines:

In August, we plan to be release an initial Expo Plugin which will include support for Content Cards, In-App Messages, Analytics, and Geofences. 

Following that release, we'll be working towards adding plugin support for Push (the next month or so).

We'll update here with each milestone, and looking forward to your teams testing out the plugin and providing any feedback!

**Comment by davidbielik** [comment]
Hi, we're excited to release the first version of our Braze Expo Plugin! You can find our documentation [here][docs]. 

To get started, simply `expo install @braze/expo-plugin` and then pass in [your configuration][docs] in your `app.json` file.

This initial release includes support for: 
* In-App Message (automatic, and custom handling)
* Content Cards (automatic, and custom handling)
* User Analytics
* Geofences/location services

Next month we'll release our support for Push Notifications in the Javascript layer.

If you have time to test out the plugin, we'd appreciate any feedback you have or improvements we should make prior to the next release. 

[docs]: https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/

**Comment by davidbielik** [comment]
Good news everyone! We're excited to announce `@braze/expo-plugin@v0.4.0` and `react-native-appboy-sdk@1.38.0` which now support Push Notifications via `Braze.requestPushPermission(options)`.

You can read more about how to integrate this in our [documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/). We hope this makes your Braze integration easier, with less native coding requirements.

Thanks again for all your feedback to help prioritize this, and if you have any questions or want to report any issues, feel free to open a github issue in our [React Native SDK](https://github.com/Appboy/appboy-react-sdk/issues/) or our new [Expo Plugin](https://github.com/braze-inc/braze-expo-plugin).
