### ISSUE TITLE
React Native Build FAILED : Could not download android-sdk-base-14.0.1.aar (com.appboy:android-sdk-base:14.0.1)

### ISSUE THREAD

**Issue by RizkyPratamaHidayat** [Appboy/appboy-react-sdk#122]
I have a issue when i build my RN project and got an error like this :

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download android-sdk-ui-14.0.1.aar (com.appboy:android-sdk-ui:14.0.1)
      > Could not get resource 'https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/14.0.1/android-sdk-ui-14.0.1.aar'.
         > Read timed out
   > Could not download android-sdk-base-14.0.1.aar (com.appboy:android-sdk-base:14.0.1)
      > Could not get resource 'https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-base/14.0.1/android-sdk-base-14.0.1.aar'.
         > Could not GET 'https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-base/14.0.1/android-sdk-base-14.0.1.aar'.
            > Connection reset
           
are there solutions for my issue above? 

Thankyou :)

**Comment by radixdev** [comment]
I can download that artifact at the time of reading. That must have been a temporary github issue.
