### ISSUE TITLE
Don't log error if there is no initial url

### ISSUE THREAD

**Issue by Minishlink** [Appboy/appboy-react-sdk#125]
Hello, please don't log false errors, such as the one when no iOS initial url is found.

Related code:
* https://github.com/Appboy/appboy-react-sdk/blob/3b28abfa5613934a237292df2cd6767dbfd96c4c/index.js#L55 
* https://github.com/Appboy/appboy-react-sdk/blob/3b28abfa5613934a237292df2cd6767dbfd96c4c/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m#L86

**Comment by Bucimis** [comment]
Thanks @Minishlink - we've added fixing this to our backlog

**Comment by wesleyorbin** [comment]
@Minishlink We just released v1.34.0, which improves fixes this issue.
