### ISSUE TITLE
Use of undeclared identifier 'Appboy' on Xcode 

### ISSUE THREAD

**Issue by pabloearg** [Appboy/appboy-react-sdk#133]
Hello,

My current configuration for iOS is:

Xcode : 13.1
"react-native": "0.65.1"
"react-native-appboy-sdk": "1.33.1"

After following all the steps required [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/)

At this line of code in Xcode: 

```
[Appboy startWithApiKey:@"YOUR-APP-IDENTIFIER-API-KEY"
         inApplication:application
     withLaunchOptions:launchOptions];
```

im getting a **_Use of undeclared identifier 'Appboy'_** error

is there any missing step in the documentation for iOS?

**Comment by wesleyorbin** [comment]
Hi @pabloearg. I'm sorry you're having this issue. Just to make sure, are you importing the SDK at the top of your file using `#import "Appboy-iOS-SDK/AppboyKit.h"`?

**Comment by pabloearg** [comment]
yes, i added the import after running  pod install

**Comment by wesleyorbin** [comment]
Hi @pabloearg. If you're still having this issue, I would recommend reaching out to our [support team](https://www.braze.com/docs/support_contact/), as they will be able to help you debug this more efficiently.
