### ISSUE TITLE
Android - getInitialNotification always returns null when opening the app with a Braze notification

### ISSUE THREAD

**Issue by judastheo** [Appboy/appboy-react-sdk#134]
Hello,

I encounter an issue only with Braze notifications. When the app is in a quit state, I receive the notification from Braze, it opens the app and when fetching the initial notification through `messaging.getInitialNotification()` from `@react-native-firebase/messaging`, it returns null in both iOS and Android.

When I send a notification directly from Firebase console, the initial notification is not null, it happens when the notification is fired from Braze.

Here the keys in the Android braze.xml
```xml
<string name="com_appboy_api_key">****</string>
<string translatable="false" name="com_appboy_custom_endpoint">****</string>
<bool name="com_appboy_enable_location_collection">true</bool>
<bool translatable="false" name="com_appboy_firebase_cloud_messaging_registration_enabled">true</bool>
<string translatable="false" name="com_appboy_firebase_cloud_messaging_sender_id">****</string>
<bool name="com_appboy_handle_push_deep_links_automatically">true</bool>
<bool name="com_appboy_push_deep_link_back_stack_activity_enabled">false</bool>
```

Is it a known issue? Is there some configuration that is either wrong or missing? Do you need more information?

Thank you very much, happy holidays!

P.S: I updated to the last versions of `react-native-appboy-sdk` and `@react-native-firebase/messaging` (and other firebase libraries), the issue still remained.

- `react-native-appboy-sdk` : from `1.31.0` to `1.33.1`
- `@react-native-firebase/messaging` : from `12.9.0` to `14.1.0`

**EDIT**

I investigated on Firebase messaging side and the Intent they received does not contain `message_id` nor `google.message_id` in the extras, hence initial notification is not set.

**Comment by wesleyorbin** [comment]
Hi @judastheo. Apologies for the delayed response. In Firebase, you can send push as "notification messages" or "data messages" - we do the latter because we don't want FCM to automatically display the app. Based on the [docs](https://firebase.google.com/docs/cloud-messaging/concept-options), we suspect that for "data messages", the `message_id` isn't sent, causing that initial notification flow to not work. This is our working theory, but we should be able to get you a more concrete answer after the holidays if that's okay.

**Comment by wesleyorbin** [comment]
@judastheo We were able to confirm that the response above is correct. I'm going to close out the issue, but feel free to re-open if you're still experiencing issues.

**Comment by judastheo** [comment]
Hello @wesleyorbin !

Thank you for your answer and the investigation. 

Just to confirm, on my side can we change something to have the `message_id` sent and not have data messages ? Or is it something global on your side?

**Comment by wesleyorbin** [comment]
Hi @judastheo. It's global on the Braze side. Can you clarify your use case for having the `message_id` sent?

**Comment by kmangatwr** [comment]
Hi @wesleyorbin we use braze to send push notifications to users, but `getInitialNotification` doesn't work as mentioned above. Is there a work around for this?
