### ISSUE TITLE
Remove iOS deprecated protocol

### ISSUE THREAD

**Issue by matinzd** [Appboy/appboy-react-sdk#136]
The following protocol in iOS is deprecated:
`- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo `

https://github.com/Appboy/appboy-react-sdk/blob/3d68180e912e10c60c92658d201628e7c1ee7872/AppboyProject/ios/AppboyProject/AppDelegate.m#L73

**Comment by wesleyorbin** [comment]
Hi @matinzd! Thanks for bringing this to our attention. We will remove this in the next release.

**Comment by wesleyorbin** [comment]
Hi @matinzd! This was fixed in v1.34.0. Thanks again for bringing this to our attention.
