### ISSUE TITLE
Is there a way to get attributes from current user?

### ISSUE THREAD

**Issue by Kevi-x** [Appboy/appboy-react-sdk#142]
We plan to implement a way to opt-in / opt-out from notifications of specific article categories. We wanted to use custom attributes for that, but I don't see a function to get the attributes back from Braze. Is there anything like that?

**Comment by wesleyorbin** [comment]
Hi @Kevi-x! Our SDKs are write-only by design. I would recommend that you reach out to our [support team](https://www.braze.com/docs/support_contact) as they will be able to help you come up with a solution for your use case.

**Comment by Bucimis** [comment]
@Kevi-x feel free to submit the functionality as a feature request in our [Public Roadmap Portal](https://dashboard.braze.com/resources/roadmap) as well
