### ISSUE TITLE
Unable to install "APPNAME" on iphone after add notification service extension for set up rich notification IOS

### ISSUE THREAD

**Issue by allandallopez** [Appboy/appboy-react-sdk#143]
Hello, I was trying to configuring rich notification for my app but then its became unable to install on my iphone after following the documentation for rich notification from braze, here is the link  : https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/rich/

1. This is the example of my xcode after add the notification service extension based on the documentation above : 
![ns](https://user-images.githubusercontent.com/45220508/154232479-21ce40cd-8382-4bd7-894b-4c176e17c93c.png)

2. And this is example when im try to install the app, after archive the build : 
![appss](https://user-images.githubusercontent.com/45220508/154232580-5fdc9caf-6c21-434d-bcfb-12dbf07b2d8c.png)

This is not happening before, but if i remove the notification extension from my xcode it will working as well as before, & if you guys curious if i am already do all the step from the documentation, the answer is i did. 

FYI, if im running my app on debug mode using iphone simulator or iphone real device there is nothing happen its running well. The error unable to install happened after im archiving the app an export it into an .ipa file then install it to my iphone.

#### Additional Information

* Nodejs version: v17.2.0
* Xcode Version: 13.1
* React version: 17.0.2
* React Native version: 0.66.3
* Platform(s): IOS
* TypeScript version: 4.4.4

**Comment by Bucimis** [comment]
@allandallopez it's hard to say exactly what's happening but signs might point to a signing issue, especially if you're able to install in debug mode.

**Comment by allandallopez** [comment]
@Bucimis I think so, especially from the Braze documentation says that we have to set up service extensions in the Apple Developer Portal. But the problem is that the documentation doesn't tell us where is it or how to set it up even the link that give just redirected to apple developer home page. Perhaps you can help with that step means actually

![Screen Shot 2022-02-16 at 18 01 26](https://user-images.githubusercontent.com/45220508/154314269-3332ba46-06b3-4ae3-b8e4-1357e06b0177.png)

**Comment by mattlsteinberg** [comment]
Hi @allandallopez, I noticed you've also reached out to our support team with this same issue. I’ll be reaching out to you shortly on that ticket with some questions and next steps.
