### ISSUE TITLE
crasher on v1.35.0 - AppboyReactBridge.setMetadata is not a function (Android)

### ISSUE THREAD

**Issue by jarredt** [Appboy/appboy-react-sdk#144]
SDK version: 1.35.0
Platform: Android

**Repro**:
- upgrade to v1.35.0
- run Android and call `logCustomEvent` or `changeUser`

**Error**: `AppboyReactBridge.setMetadata is not a function` (see attached screenshot)

**Cause**: 1.35.0 added the `setMetadata` function to the iOS native bridge, but not to the Android native bridge (see https://github.com/Appboy/appboy-react-sdk/commit/7d99123fd646f930eb6dacb130fbf74ca809e2d0). The library calls `setMetadata` in `changeUser` and `logCustomEvent`, so we can't use those methods without getting this error on Android.

![Screen Shot 2022-03-15 at 11 32 05 AM](https://user-images.githubusercontent.com/16692671/158448551-c5b54a68-bbb2-492a-b07f-61755ab3e1f7.png)

**Comment by wesleyorbin** [comment]
Hi @jarredt. Thanks for raising this. We'll have a fix out for this ASAP.
