### ISSUE TITLE
Need a getPushNotificationSubscriptionType() method

### ISSUE THREAD

**Issue by hongbinhuang** [Appboy/appboy-react-sdk#146]
There is a [setPushNotificationSubscriptionType() API](https://github.com/Appboy/appboy-react-sdk/blob/171784d932cc91e2c5e14e8e0125744565110cc6/android/src/main/java/com/appboy/reactbridge/AppboyReactBridge.java#L468), but there is no getter. 
Use case: need the getter to show user the current state upon re-login (could be on a new device).

**Comment by wesleyorbin** [comment]
Hi @hongbinhuang. For security reasons, our SDKs are write-only in regard to user data. You can submit a feature request [here](https://dashboard.braze.com/resources/roadmap) to add support for this in the future. For now, we would recommend displaying to the user whether the current device is registered for push.
