### ISSUE TITLE
Push Notification is received, but not showing in Android?

### ISSUE THREAD

**Issue by lahiurban** [Appboy/appboy-react-sdk#147]
```
{
    "notification": {
        "title": "Test title",
        "body": "Test mobile"
    }
}
```

Do we need this JSON format to read a push notification message? But in braze, I am getting a different format

**Comment by Bucimis** [comment]
@lahiurban are you sending that payload manually through FCM or through the Braze API/dashboard? When sending push to FCM, the Braze servers includes a special key which ultimately let the SDK know the push is from Braze, if that key is not included, the SDK will not ask the OS to display the notification. You should be able to see this in the verbose logs.

**Comment by lahiurban** [comment]
Sending from the braze dashboard. I got a success message from the braze dashboard after sending the push notification campaign and received it to the Android mobile app firebase background handler, but push pop up does not appear. here is the payload that I received.

`{
"sentTime":xxxxxxx,
"data":{
"t":"Dev Android App",
"p":"0",
"cid":"xxxxxxxxxx",
"ab_nc":"com_appboy_default_notification_channel",
"_ab":"true",
"a":"Braze has launched!!!"
},
"from":"xxxx",
"messageId":"xxxxx",
"ttl":2419200,
"collapseKey":"campaign"
}`
