### ISSUE TITLE
[push notification] with sound

### ISSUE THREAD

**Issue by zrg-team** [Appboy/appboy-react-sdk#148]
+ Is there any document for sound in push-notification react-native sdk

**Comment by Bucimis** [comment]
@zrg-team sound should be set through configuration on the native side - check out our Android and iOS docs:

https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings#sounds
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/customization/custom_sounds#custom-sounds
