### ISSUE TITLE
Handling two firebase messaging service

### ISSUE THREAD

**Issue by lclrobert2020** [Appboy/appboy-react-sdk#150]
In order for braze to work, it requires
```
<service android:name="com.braze.push.BrazeFirebaseMessagingService"
  android:exported="false">
  <intent-filter>
    <action android:name="com.google.firebase.MESSAGING_EVENT" />
  </intent-filter>
</service>
```
But for another common installed package, @react-native-firebase/messaging, it also need a service on the same action
https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/AndroidManifest.xml

```
    <service android:name=".ReactNativeFirebaseMessagingService"
             android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
    </service>

```

They both have a intent-filter on the same ``` com.google.firebase.MESSAGING_EVENT```
From what i have experimented, if the same app is having two service using the same action in the intent filter,
only one service will be called.

From what I have read from the braze instruction, for native android project , i can use my own FirebaseMessagingService and pass the received information to Braze
```
public class MyFirebaseMessagingService extends FirebaseMessagingService {
  @Override
  public void onMessageReceived(RemoteMessage remoteMessage) {
    super.onMessageReceived(remoteMessage);
    if (BrazeFirebaseMessagingService.handleBrazeRemoteMessage(this, remoteMessage)) {
      // This Remote Message originated from Braze and a push notification was displayed.
      // No further action is needed.
    } else {
      // This Remote Message did not originate from Braze.
      // No action was taken and you can safely pass this Remote Message to other handlers.
    }
  }
}
```
But in this case, the @react-native-firebase/messaging is another package and it already has its own FirebaseMessagingService implementation , how can I make braze and @react-native-firebase/messaging work together without manually rewriting @react-native-firebase/messaging 's FirebaseMessagingService  implementation

**Comment by radixdev** [comment]
Hi @lclrobert2020 ,

You are correct in that having multiple of those intent filters can lead to issues. I would recommend using [`tools:node="remove"`](https://developer.android.com/studio/build/manage-manifests) on the other library's FirebaseMessagingService in order to remove it from the merged manifest.
