### ISSUE TITLE
Assigning to 'id<ABKInAppMessageControllerDelegate> _Nullable' from incompatible type 'AppDelegate *const __strong'

### ISSUE THREAD

**Issue by ziyoshams** [Appboy/appboy-react-sdk#151]
I am getting this error 
```
Assigning to 'id<ABKInAppMessageControllerDelegate> _Nullable' from incompatible type 'AppDelegate *const __strong'
```

while doing this:
<img width="1001" alt="Screen Shot 2022-05-25 at 1 15 03 AM" src="https://user-images.githubusercontent.com/14338593/170124100-247fec1e-ac37-467a-aaef-814c0194da5b.png">

```
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.47 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
``` 

Any workarounds?

**Comment by Bucimis** [comment]
@ziyoshams did you declare that your class implements ABKInAppMessageControllerDelegate? See e.g. https://github.com/Appboy/appboy-ios-sdk/blob/4c5fa9bdd80612cd6816159ce99b9c7a80af60c6/Samples/InAppMessage/BrazeInAppMessageSample/BrazeInAppMessageSample/AppDelegate.h#L4

**Comment by ziyoshams** [comment]
@Bucimis is that a replacement for `#import <UserNotifications/UserNotifications.h>` ?

**Comment by Bucimis** [comment]
@ziyoshams it's not a replacement, you still need to implement `UNUserNotificationCenterDelegate` for push, and import the corresponding `UserNotifications` framework.  `ABKInAppMessageControllerDelegate` is for in-app messages, a separate feature from push.
