### ISSUE TITLE
[iOS] Content Card doesn't reload

### ISSUE THREAD

**Issue by thanhhuan1990** [Appboy/appboy-react-sdk#153]
Situation:

Platform: iOS
SDK version: 1.34.0
Feature: Content Card

1. Register Push notifications for iOS & Android App
2. Listen to event CONTENT_CARDS_UPDATED
3. Sent a message with type = INBOX from Braze to both iOS & Android devices

Expectation:

- Both 2 devices will display notifications and reload the Content Card list

Actual result:
- Android: Display Notification and Content Card are reloaded: → OK
- iOS: Notification displayed, but Content Card is Empty, even after calling **requestContentCardsRefresh** manually, nothing displayed

Please help to fix or share your ideas.
Thank you

**Comment by Bucimis** [comment]
@thanhhuan1990 could you reach out to support@braze.com with a description of the issue and verbose logs from iOS showing the runtime behavior you're running into? https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations#verbose-logging Thanks!
