### ISSUE TITLE
Braze - IAM iOS/Android

### ISSUE THREAD

**Issue by matsmello** [Appboy/appboy-react-sdk#162]
Hello team, I am using Braze to send push notifications and in-app messages.
I did the integration and I am receiving the push notifications but every time that I send a new IAM I receive the content from the logs on react native side but I don't see any visual content.

results from `console.log`:

```
{"inAppMessage": {"buttons": [], "clickAction": "none", "dismissType": "swipe", "duration": 5000, "extras": {}, "header": "My Header", "imageUrl": "", "inAppMessageJsonString": "{\"text_align_message\":\"CENTER\",\"header_text_color\":4280624421,\"text_color\":4280624421,\"crop_type\":\"FIT_CENTER\",\"close_btn_color\":4291085508,\"duration\":5000,\"use_webview\":false,\"text_align_header\":\"CENTER\",\"trigger_id\":\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==\",\"image_style\":\"TOP\",\"bg_color\":4294243575,\"message_close\":\"swipe\",\"type\":\"modal\",\"frame_color\":3207803699,\"animate_in\":true,\"animate_out\":true,\"message\":\"My current body\",\"header\":\"My Header\",\"click_action\":\"none\",\"is_control\":false}", "message": "My current body", "messageType": "modal", "uri": "", "useWebView": false, "zippedAssetsUrl": ""}}
```

I tested on iOS and on Android, in both platforms I received the push notifications but none of them are rendering the IAM content.

Do you have any suggestions?

**Comment by wesleyorbin** [comment]
Hi @matsmello. Can you share your `subscribeToInAppMessage()` snippet?

**Comment by matsmello** [comment]
```
  Braze.subscribeToInAppMessage(false, event => {
    const inAppMessage = new Braze.BrazeInAppMessage(event.inAppMessage);
    console.log({ inAppMessage });
  });
```
As you can see, the console.log is logging the message that I printed above.
Thank you, @wesleyorbin for your attention.

**Comment by wesleyorbin** [comment]
@matsmello The first parameter to `subscribeToInAppMessage()` tells the SDK whether or not to display IAMs with the Braze UI. If you flip it to `true`, you will see the IAMs being displayed. A value of `false` should only be used if you want to display IAMs with a custom UI.
