### ISSUE TITLE
Warning NativeEventEmitter with non-null argument

### ISSUE THREAD

**Issue by hermanbanken** [Appboy/appboy-react-sdk#163]
> WARN `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 

This is triggered from this piece of code:

https://github.com/Appboy/appboy-react-sdk/blob/a0c724c81450cf6b4353addbbc67a9cf6eac6e90/src/braze.js#L37-L40

**Comment by wesleyorbin** [comment]
Hi @hermanbanken. Thank you for reaching out. We've filed a ticket internally to fix this warning.

**Comment by jarredt** [comment]
The answer here should be all you need to do -- just add these empty methods to your Android module: https://stackoverflow.com/questions/71263427/new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-requi

**Comment by wesleyorbin** [comment]
Hi @hermanbanken @jarredt. We just released a fix for this in 1.39.0. Let me know if you encounter any issues after upgrading.

**Comment by wesleyorbin** [comment]
Hi @sonnguyprophet. This looks like a different error. Feel free to open a new issue or file a ticket with our [support team](https://www.braze.com/docs/support_contact) and include any relevant code samples as well as the versions of the SDK and React Native you are running.
