### ISSUE TITLE
Issue compiling on android.

### ISSUE THREAD

**Issue by juanch0x** [Appboy/appboy-react-sdk#165]
Hi! 
I'm having some troubles when compiling.

I'm using 
```
"react-native": "0.64.3",
"react-native-appboy-sdk": "^1.38.0"
```

After follow [this](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#step-1-integrate-the-braze-library) instructions I end up with this `build.gradle` file

```
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath("com.google.gms:google-services:4.3.10")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../android"))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(["node", "--print", "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), "../dist"))
        }

        google()
        mavenCentral()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
        maven { url 'https://maven.google.com' }
    }

```

But when I try to compile, or to run a ./gradle clean in the android folder I'm getting the following error

> 
> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/Users/jportugal/Documents/nonerds/code/loper-app/node_modules/react-native-appboy-sdk/android/build.gradle' line: 2
> 
> * What went wrong:
> A problem occurred evaluating project ':react-native-appboy-sdk'.
> > Plugin with id 'kotlin-android' not found.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':react-native-appboy-sdk'.
> > compileSdkVersion is not specified. Please add it to build.gradle
> 

I try to install kotlin dependency but isn't work, anybody knows what can I do?

Thanks for your time guys!

**Comment by juanch0x** [comment]
I was able to add the kotlin plugin with and the error now changes to

> e: /Users/jportugal/Documents/nonerds/code/loper-app/node_modules/react-native-appboy-sdk/android/src/main/java/com/appboy/reactbridge/BrazeReactBridge.kt: (417, 42): Unresolved reference: hasActiveReactInstance

**Comment by radixdev** [comment]
Hi @juanch0x ,

It looks like that method was added in 0.65.0 of the react dependency. See https://www.reactnative.com/react-native-v0-65-x-released. You may need to upgrade

**Comment by juanch0x** [comment]
Hello, thank you! I end up downgrading to
```
 "react-native-appboy-sdk": "1.34.1"
```
and everything works fine!

**Comment by grashupfer99** [comment]
I was able to successfully build my project with version: `1.37.0`.

#### My project settings:
- `"react-native": "0.63.4",`
- `"react-native-appboy-sdk": "1.37.0",`

#### build.gradle (MyProjectName):
```gradle
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
        classpath 'com.google.gms:google-services:4.3.5'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven { url("$rootDir/../node_modules/react-native/android") }
        maven { url("$rootDir/../node_modules/jsc-android/dist") }
        google()
        jcenter()
        maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
        maven { url 'https://www.jitpack.io' }
    }
}
```
