### ISSUE TITLE
Anything besides default export results in functions being undefined

### ISSUE THREAD

**Issue by adammatheson** [Appboy/appboy-react-sdk#166]
```javascript
import { requestPushPermission } from 'react-native-appboy-sdk'
requestPushPermission(permissionOptions)
```

... results in:

`[TypeError: (0, _reactNativeAppboySdk.requestPushPermission) is not a function. (In '(0, _reactNativeAppboySdk.requestPushPermission)(permissionOptions)', '(0, _reactNativeAppboySdk.requestPushPermission)' is undefined)]`

-----

```javascript
import Braze from 'react-native-appboy-sdk'
const {requestPushPermission} = Braze;
requestPushPermission(permissionOptions)
```

... results in:

`TypeError: undefined is not an object (evaluating '_reactNativeAppboySdk.Braze.requestPushPermission')`

-----

```javascript
import Braze from 'react-native-appboy-sdk'
Braze.requestPushPermission(permissionOptions)
```

This works, but my IDE complains because I have [import/no-named-as-default-member](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/no-named-as-default-member.md) enabled.

Is this intended?

```
// package.json
"react-native-appboy-sdk": "1.38.0",

PODS:
  - Appboy-iOS-SDK (4.5.0):
    - Appboy-iOS-SDK/UI (= 4.5.0)
  - Appboy-iOS-SDK/ContentCards (4.5.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/Core (4.5.0)
  - Appboy-iOS-SDK/InAppMessage (4.5.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/NewsFeed (4.5.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/UI (4.5.0):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
```

**Comment by wesleyorbin** [comment]
Hi @adammatheson. Currently the SDK only exports `Braze` as the default export. We have it on our roadmap to export methods and classes individually in the future. We could also export `Braze` as a named export if that would solve your issue in the short term.

**Comment by adammatheson** [comment]
@wesleyorbin Hmm strange. I'm sure I was doing this in 1.36.0 last time I used it. If this is intended behaviour then you can close the issue, I just added `/* eslint-disable import/no-named-as-default-member */` to this file for now.

**Comment by drweizak** [comment]
This problem still persists in version 9.1.0! Can someone else confirm it?
Any plan in the future.

**Comment by vanessaland** [comment]
Hi @drweizak,

The Braze React Native SDK currently does not export methods and classes individually. It still is on our roadmap to support in the future, but has been deprioritized so we don't have a timeline we can share yet. 

You will have the import `Braze` and access methods in this way:

```typescript
import Braze from '@braze/react-native-sdk';
...
Braze.requestPushPermission(options);
```
Please let us know if you are having any issues. Thank you!

**Comment by drweizak** [comment]
> Hi @drweizak,
> 
> The Braze React Native SDK currently does not export methods and classes individually. It still is on our roadmap to support in the future, but has been deprioritized so we don't have a timeline we can share yet.
> 
> You will have the import `Braze` and access methods in this way:
> 
> ```ts
> import Braze from '@braze/react-native-sdk';
> ...
> Braze.requestPushPermission(options);
> ```
> 
> Please let us know if you are having any issues. Thank you!

Thank you so much for letting me know!
No issues at the moment!
