### ISSUE TITLE
Email is not showing up in Braze Dashboard

### ISSUE THREAD

**Issue by othman95** [Appboy/appboy-react-sdk#169]
Hello, I'm using 
`"react-native": "0.69.4",
"react-native-appboy-sdk": "^1.38.0"`

I followed the instructions to set up push notifications on Android but then i noticed that the email is not showing up in Braze for any user, all other events and information are showing. And push notifications are working as expected.

`
    public void onCreate() {
    super.onCreate();
    // If you opted-in for the New Architecture, we enable the TurboModule system
      BrazeLogger.setLogLevel(Log.VERBOSE);

      final Context applicationContext = this;
      FirebaseMessaging.getInstance().getToken().addOnCompleteListener(task -> {
          if (!task.isSuccessful()) {
              Log.w("BRAZE", "Exception while registering FCM token with Braze.", task.getException());
              return;
          }
          else {
              Log.w("BRAZE", "Successfully registered with FCM.");
          }

          final String token = task.getResult();
          Braze.getInstance(applicationContext).setRegisteredPushToken(token);
      });
`

and im calling several methods from react native side such as ReactAppBoy.setFirstName and ReactAppBoy.setLastName and ReactAppBoy.setEmail and so on, all are working except the ReactAppBoy.setEmail. After all these im calling ReactAppBoy.changeUser.

i noticed one thing in the logs, the email is sent in a field called last_name:
`
    to url: https://sdk.fra-02.braze.eu/api/v3/data
                
    with headers:
    "Accept-Encoding" => "gzip, deflate"
    "Content-Type" => "application/json"
    "X-Braze-Api-Key" => "f3b1f242-5816-4163-b102-20e688feb920"
    
    and JSON :
    {
      "device_id": "2ca1d1ae-c202-4969-b30a-1d8104041a04",
      "time": 1662646136,
      "api_key": "f3b1f242-5816-4163-b102-20e688feb920",
      "sdk_version": "23.0.1",
      "app_version": "1.9",
      "app_version_code": "19.0.0.0",
      "attributes": [
        {
          "last_name": "t@t156.com",
          "user_id": "CU157950"
        }
      ],
      "sdk_flavor": "react",
      "respond_with": {
        "user_id": "CU157950",
        "config": {
          "config_time": 1658336849
        }
      }
    }
`

Would that be the issue ?

**Comment by wesleyorbin** [comment]
Hi @othman95. Thanks for bringing this to our attention. We will deploy a fix for this soon.

**Comment by othman95** [comment]
![image](https://user-images.githubusercontent.com/40391125/189152181-8ea944a6-5bd6-42c6-b6c5-65162ef543c5.png)

please check this, i think it's the culprit, it's in BrazeReactBridge.kt, line 241

**Comment by wesleyorbin** [comment]
Hi @othman95. We just released 1.38.1, which fixes this issue. Thank you again for bringing this to our attention!
