### ISSUE TITLE
Invalid API key error when using correct ID

### ISSUE THREAD

**Issue by SMJ93** [Appboy/appboy-react-sdk#17]
I have set up Appboy on iOS by following the [instructions](https://www.appboy.com/documentation/React_Native/iOS/):

1. Install the Appboy iOS SDK into your iOS project. using manual integration
2. npm install react-native-appboy-sdk@latest --save
3. Add AppboyReactBridge.xcodeproj library to my xcode project
4. Add libAppboyReactBridge.a to Build Phases -> Link Binary With Libraries
5. AppboyKit is in the root (alongside Libraries, Frameworks etc.) so I have not updated the ‘Header Search Paths’

Everything seems to be working ok:

```
2017-07-27 15:44:23.519 [info][tid:main][AppboyReactBridge.m:55] [Appboy sharedInstance] changeUser with value 46456546546464bsdfd5654g6fd564efs5
2017-07-27 15:44:23.519403+0100 aMobile[2944:784709] [Appboy sharedInstance] changeUser with value 46456546546464bsdfd5654g6fd564efs5
2017-07-27 15:44:23.519498+0100 aMobile[2944:784709] [APPBOY] Got request to switch to the current user ID. There is nothing to transition, returning without action
2017-07-27 15:44:23.520 [info][tid:main][AppboyReactBridge.m:66] [Appboy sharedInstance] logCustomEvent with eventName cordovaCustomEventWithProperties
2017-07-27 15:44:23.519636+0100 aMobile[2944:784709] [Appboy sharedInstance] logCustomEvent with eventName cordovaCustomEventWithProperties
2017-07-27 15:44:23.521 [info][tid:main][AppboyReactBridge.m:77] [Appboy sharedInstance].user.firstName =  firstName
2017-07-27 15:44:23.521091+0100 aMobile[2944:784709] [Appboy sharedInstance].user.firstName =  firstName
2017-07-27 15:44:23.524 [info]
```

But then I get an API key error:

```
[APPBOY] Invalid API key
```

Inside App Settings on the [Appboy dashboard](https://dashboard.appboy.eu/app_settings/app_settings) I have tried both the App Group Identifier and the iOS application identifier, but I still always get the same error.

Here is my `AppDelegate.m` file:

```
#import "AppDelegate.h"
#import "CodePush.h"
#import "AppboyKit.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  NSURL *jsCodeLocation;

  
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"aMobile"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  
  UIViewController *rootViewController = [UIViewController new];
  
  rootViewController.view = rootView;
  
  self.window.rootViewController = rootViewController;
  
  [self.window makeKeyAndVisible];
  
  [Appboy startWithApiKey:@"MY_KEY_FROM_DASHBOARD"
            inApplication:application
        withLaunchOptions:launchOptions];
  
  return YES;
}

@end

```

Is there something else I need to send?

Cheers, 

Stu

**Comment by tiffanylu** [comment]
Hi @SMJ93,

The API key that should be passed into `startWithApiKey:inApplication:withLaunchOptions:` is the API key under Manage App Group > App Settings, per the documentation [here](https://www.appboy.com/documentation/Platform_Wide/#step-2-add-your-apps). 

We recommend that integration issues, such as the one you are experiencing above, are directed to support@appboy.com. Unlike GitHub, that channel is optimized to address integration issues, and there is no risk of leaking sensitive data (e.g., API keys or app code). 

If the above information does not solve the issue, please email support@appboy.com with full device logs and your Appboy integration code, including all methods from where you are making Appboy calls. 

Best,
Tiff

**Comment by SMJ93** [comment]
Hi @tiffanylu, thanks for the quick response!

Yes that is the key I am using. We are using an EU data centre so need to pass through further config. I recommend adding this step to your main documentation as it is buried away [here](https://www.appboy.com/documentation/FAQs/#rest-apis).

**Comment by foggy1** [comment]
Just wanted to follow up and say that https://www.braze.com/documentation/FAQs/#rest-apis the tables containing information about SDK endpoints contained in the FAQ should 100% be within the SDK implementation walkthrough. Even the xml examples mention including "com_appboy_api_key" and never say anything about "com_appboy_custom_endpoint."

**Comment by db42** [comment]
Thanks @SMJ93

**Comment by trustfall** [comment]
Yeah, also had this issue myself, should in the docs for sure.

**Comment by Bucimis** [comment]
Hi @SMJ93 @db42 @trustfall,

Thanks for raising, we've updated the following section to include APi endpoint information - https://www.braze.com/documentation/Android/#step-2-configure-the-braze-sdk-in-appboyxml

**Comment by Lolz246** [comment]
What happens if anyone gets braze API Key?
