### ISSUE TITLE
Cannot close session

### ISSUE THREAD

**Issue by othman95** [Appboy/appboy-react-sdk#171]
In an app that has sign in and sign up process, if user X sign up and then signs in, he would go from anonymous user to registered user in braze. if on the same phone, the user signs out then decides to sign up for another account, how can i change his status back to anonymous before the sign up process ? I know in React Native's SDK there's no official way to do that other than calling changeUser with a different user id, but I'm looking for a workaround.

i'm using:
`
react-native: 0.69.4
react-native-appboy-sdk: 1.38.0,
`

**Comment by wesleyorbin** [comment]
Hi @othman95. You can call `wipeData()` as a way to change a user's status back to anonymous. Note that this will create a new user/device on the Braze dashboard. If you have further questions, I'd recommend you reach out to our [support team](https://www.braze.com/docs/support_contact) and they will be happy to help you come up with the best solution for your use case.
