### ISSUE TITLE
addInAppMessage is supported?

### ISSUE THREAD

**Issue by MaggyH** [Appboy/appboy-react-sdk#173]
Hi I would like to ask about "addInAppMessage" of Braze

please refer to the below link

https://appboy.github.io/appboy-android-sdk/kdoc/braze-android-sdk/com.braze.ui.inappmessage/-braze-in-app-message-manager/add-in-app-message.html

Thanks in advance

**Comment by radixdev** [comment]
Hi @MaggyH ,

This method is currently not supported in the React layer and would require native code on your end to facilitate.
