### ISSUE TITLE
In app message not triggered while the app is closed for custom ui

### ISSUE THREAD

**Issue by dasuntn** [Appboy/appboy-react-sdk#180]
Hello,
I use Braze to send push notifications and in-app messages(rendered on my custom UI).
When the app is in the background or foreground, it seems to work fine and I can access the IAM data.
But when the app is closed and I receive the push notification and I open the app using clicking on push notification but the following code is not triggered.
Tested both in ios and android seems to be the same behavior.

`  const sub = Braze.subscribeToInAppMessage(false, (event: any) => {
      const inAppMessage = new Braze.BrazeInAppMessage(event.inAppMessage);
      setInAppMsg(inAppMessage);
    });`

**Comment by wesleyorbin** [comment]
Hi @dasuntn. I'm sorry you're having this issue. I would recommend that you reach out to our [support team](https://www.braze.com/docs/support_contact) and provide them with verbose logs showing the issue, where in the app lifecycle you are instantiating `sub`, and a link to the affected campaign.
