### ISSUE TITLE
Cannot initialize a parameter of type 'id<RCTBridgeDelegate>' with an lvalue of type 'AppDelegate *const __strong'

### ISSUE THREAD

**Issue by pabloearg** [Appboy/appboy-react-sdk#183]
Hi Braze Team, 

React native version: 0.69.5
New Architecture: OFF
"react-native-appboy-sdk": "1.38.0",

Im trying to implement Push Notifications in our react native app, but im getting the **_Cannot initialize a parameter of type 'id<RCTBridgeDelegate>' with an lvalue of type 'AppDelegate *const __strong'_** error in the AppDelegate.mm after adding  UNUserNotificationCenterDelegate to our AppDelegate.h

```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, UNUserNotificationCenterDelegate, RCTBridgeDelegate>

```
![image](https://user-images.githubusercontent.com/29818262/196521244-ca7a0e15-42fb-4acf-a99a-f742eee81b1f.png)

I checked your sample app, and I don't know why you dont have the 

`  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
`
line there. How can I solved this issue?

**Comment by wesleyorbin** [comment]
Hi @pabloearg. We use [this](https://github.com/facebook/react-native/blob/main/React/Base/RCTRootView.h#L75) `RCTRootView` convenience initializer, which creates a bridge internally. However, this method does have some caveats as listed in the comments there. Did you update your `AppDelegate.h` file to implement the `RCTBridgeDelegate` interface?

**Comment by pabloearg** [comment]
I fixed by adding:

`@synthesize bridge;
`

below:

`@implementation AppDelegate`
