### ISSUE TITLE
[Bug]: Dismiss Content Cards Modal Android

### ISSUE THREAD

**Issue by janvandertaelen** [Appboy/appboy-react-sdk#186]
### Platform

Android

### React Native Version

0.69.6

### Braze SDK Version

1.40

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "react-native-appboy-sdk"`.
  2. `Braze.changeUser("id")`
  3. `Braze.launchContentCards()`

Not possible to dismiss the content cards modal on Android. On iOS the modal has a done button to dismiss it but on android nothing is present to dismiss the modal.

### Expected Behavior

We need an easy way that is clear for the user to dismiss the content cards modal on Android

### Actual Incorrect Behavior

Not able to dismiss the content cards modal on Android

**Comment by wesleyorbin** [comment]
Hi @janvandertaelen. The content cards screen can be dismissed using the Android back button.
