### ISSUE TITLE
Expose 'NewsFeed' as View/Embeddable 

### ISSUE THREAD

**Issue by brianjd** [Appboy/appboy-react-sdk#2]

**Comment by tiffanylu** [comment]
Hi @brianjd,

Thanks for making this request! Our News Feed's UI and functionality are reliant on the Feed View Controller. As such, the News Feed cannot be easily exposed as a standalone native view, nor does React currently appear to support bridging native view controllers (see https://github.com/facebook/react-native/issues/1148). 

Our React bridge does support [launching the News Feed](https://github.com/Appboy/appboy-react-sdk/blob/master/index.js#L266) from within React Native. Could you please let us know what additional functionality you’re looking for, or if there are specific News Feed-related models or properties we could expose to help you achieve your use case?

Best,
Tiff

**Comment by tiffanylu** [comment]
Hi @brianjd,

Per the discussion above, I'm going to close this issue. If you run into similar issues in the future or want to convey your specific use-case to us, please feel free to contact support@appboy.com. Thanks again for reporting this!

Best,
Tiff
