### ISSUE TITLE
Release 1.4.0?

### ISSUE THREAD

**Issue by jimmy-devine** [Appboy/appboy-react-sdk#22]
Hi Appboy Team,

I need the newly-added `.podspec` file. But it looks like it has yet to be officially released. Right now, `yarn install` does not include those changes when including `react-native-appboy-sdk` in my `package.json` so I have to refer to a specific commit SHA to get it to work which feels brittle.

Is it possible to cut a new release? Thank you!

**Comment by tiffanylu** [comment]
Hi @jimmy-devine, 

Thanks for opening this issue! We're planning on releasing later this week. Does that timeline work for you?

Best,
Tiff

**Comment by jimmy-devine** [comment]
Thank you so much for the update! Sounds great.
