### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by trustfall** [Appboy/appboy-react-sdk#27]
The documentation on your site should be updated with `rnpm link` references, as it has been deprecated for over a year now. React Native how has linking built in: https://facebook.github.io/react-native/docs/linking-libraries-ios.html. May I suggest updating your documentation to reflect this process, so people aren't adding `rnpm` to a project where it's not necessary? (I believe they updated this around v0.29 or so)

**Comment by foggy1** [comment]
+1

react-native link is sufficient and performs necessary actions cross-platform

**Comment by Bucimis** [comment]
We've removed `rnpm` from the public integration docs, thanks all for your input
