### ISSUE TITLE
[Bug]: ITMS-91056: Invalid privacy manifest, ITMS-91064: Invalid tracking information

### ISSUE THREAD

**Issue by QSuraj** [Appboy/appboy-react-sdk#279]
### Which Platforms?

iOS

### Which React Native Version?

0.69.12

### Which @braze/react-native-sdk SDK version?

8.4.0

### Repro Rate

100% of the time

### Steps To Reproduce

Steps: 
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  3. Run the app.
  4. I have already added the PrivacyInfo
<img width="699" alt="image" src="https://github.com/user-attachments/assets/05c11dfa-a2f6-42a0-ba6b-f1ea98871c51">

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<true/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeCoarseLocation</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeProductPersonalization</string>
				<string>NSPrivacyCollectedDataTypePurposeAnalytics</string>
			</array>
		</dict>
	</array>
	<key>NSPrivacyTrackingDomains</key>
	<array>
		<string>sdk-tracking.iad-05.braze.com</string>
	</array>
</dict>
</plist>

```

### Expected Behavior

There should be no error while uploding to App Store.

### Actual Incorrect Behavior

Gets following error after uploading to App store -

<img width="707" alt="image" src="https://github.com/user-attachments/assets/3fe824e2-d072-4dfc-a0ba-e58aad27f972">

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “BrazeLocation.bundle/PrivacyInfo.xcprivacy”. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “BrazeKit.bundle/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by jerielng** [comment]
Hey @QSuraj, this has been resolved as of [10.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/10.0.0), which was addressed in the underlying [Swift SDK](https://github.com/braze-inc/braze-swift-sdk/compare/8.4.0...9.0.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed). If you are still facing this issue after upgrading to the latest, feel free to reach back out. Thanks!

**Comment by QSuraj** [comment]
@jerielng Getting following error 
```
Invalid `braze-react-native-sdk.podspec` file: undefined method `install_modules_dependencies' for module Pod.
```

**Comment by QSuraj** [comment]
Reopened a new issue - https://github.com/braze-inc/braze-react-native-sdk/issues/280
