### ISSUE TITLE
Update Android SDK UI dependency

### ISSUE THREAD

**Issue by scascketta** [Appboy/appboy-react-sdk#28]
Hello!

I'm integrating Braze into a native Android app that also uses React Native. Per the Android documentation, I am using `com.appboy:android-sdk-ui:2.2.2`. However, this React Native SDK still references version 2.1.4. It would be great if this project could be updated to reference the latest version of the Android SDK so that users don't have to downgrade.

Thank you!

**Comment by Bucimis** [comment]
Hi @scascketta,

We've just released a new react native SDK that references Android SDK 2.2.4.

Our React Project hardcodes Android SDK versions for maximum stability. We'll consider loosening up that requirement in the future, but for now feel free to shout whenever you need an upgrade.

Thanks!
Braze SDK team

**Comment by scascketta** [comment]
I see, thank you for the update!
