### ISSUE TITLE
how to register for push notification

### ISSUE THREAD

**Issue by guizmo** [Appboy/appboy-react-sdk#30]
I have installed appboy and set up my ios app for PN, managed to set a user ID but user is not registered for push notifications.
I am quit confused by the lack of documentation for the push notification actually.
Does it have to be done via native code or on react side ?
Any help would be appreciated

<img width="382" alt="screen shot 2018-03-07 at 07 43 23" src="https://user-images.githubusercontent.com/699063/37058240-fde60bea-21dd-11e8-918e-70c7d771f845.png">

<img width="582" alt="screen shot 2018-03-07 at 07 48 02" src="https://user-images.githubusercontent.com/699063/37058249-0640e58a-21de-11e8-81f4-6888381e8675.png">

**Comment by guizmo** [comment]
And also i get the following in xcode console

 ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **     before Appboy was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************

**Comment by Bucimis** [comment]
Hi @guizmo,

Push registration and app initialization occur in native code. You will need to create an `AppDelegate` file and 1) initialize the SDK using `startWithApiKey` 2) register for push from within that file.

Check out the `AppDelegate` file in our sample app for an example implementation: https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/ios/AppboyProject/AppDelegate.m

Let us know if you have any further questions.

Thanks,
Braze SDK Engineering

**Comment by guizmo** [comment]
Ok , might be a long day for you ;)
And what is that function for on the javascript SDK ? registerPushToken(token)

Here is my appdelegate.m

`/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "SplashScreen.h"
#import "Appboy-iOS-SDK/AppboyKit.h"
#import "AppboyReactUtils.h"


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"DumbeaMall"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  [SplashScreen show];
  
  // Register for user notifications
  if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_9_x_Max) {
    UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
    center.delegate = self;
    [center requestAuthorizationWithOptions:(UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge)
                          completionHandler:^(BOOL granted, NSError * _Nullable error) {
                            NSLog(@"Permission granted.");
                          }];
    [[UIApplication sharedApplication] registerForRemoteNotifications];
  } else if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_7_1) {
    UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeBadge | UIUserNotificationTypeAlert | UIUserNotificationTypeSound) categories:nil];
    [[UIApplication sharedApplication] registerForRemoteNotifications];
    [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
  } else {
    [[UIApplication sharedApplication] registerForRemoteNotificationTypes:
     (UIRemoteNotificationTypeAlert |
      UIRemoteNotificationTypeBadge |
      UIRemoteNotificationTypeSound)];
  }

  [Appboy startWithApiKey:@"8c704fd0-7fd8-40cb-9095-0db0ef735921"
            inApplication:application
        withLaunchOptions:launchOptions];


  return YES;
}

- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  [[Appboy sharedInstance] registerApplication:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  [[Appboy sharedInstance] userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  [[Appboy sharedInstance] registerApplication:application didReceiveRemoteNotification:userInfo];
}

- (void) application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  NSLog(@"didRegisterForRemoteNotificationsWithDeviceToken.");
  NSLog(@"%@", deviceToken);
  [[Appboy sharedInstance] registerPushToken:[NSString stringWithFormat:@"%@", deviceToken]];
}


// Deep linking
/*- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  NSLog(@"Calling RCTLinkingManager with url %@", url);
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
 */

// Universal links
/*- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
 */

@end
`

part of my console 


2018-03-07 08:52:36.296 [info][tid:main][AppboyReactBridge.m:56] [Appboy sharedInstance] changeUser with value guillaumebartolini@gmail.com
2018-03-07 08:52:36.295790+1100 DumbeaMall[1589:1292968] [Appboy sharedInstance] changeUser with value guillaumebartolini@gmail.com
2018-03-07 08:52:36.295884+1100 DumbeaMall[1589:1292968] [APPBOY] 
     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **     before Appboy was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************
2018-03-07 08:52:36.582108+1100 DumbeaMall[1589:1293045] Permission granted.
2018-03-07 08:52:36.625784+1100 DumbeaMall[1589:1292968] didRegisterForRemoteNotificationsWithDeviceToken.
2018-03-07 08:52:36.625878+1100 DumbeaMall[1589:1292968] <4a1b8a7d fd7e382e 63e98654 a6805eca 76ccbc04 416d3bf9 c2d07bdd badf1e19>


but my user is still unregistered
<img width="532" alt="screen shot 2018-03-07 at 09 10 07" src="https://user-images.githubusercontent.com/699063/37061568-00a796be-21e8-11e8-8be1-d0ecfcdd3517.png">
<img width="390" alt="screen shot 2018-03-07 at 09 05 21" src="https://user-images.githubusercontent.com/699063/37061572-0321c216-21e8-11e8-890d-4f1246b84ac0.png">
 
If in my react code i dont .changeUser, i do get a new user able to receive my campaign... But i never receive it on my phone

**Comment by guizmo** [comment]
i managed to get a Push Changelog:

Received 'BadDeviceToken' sending to 'af97951713e02543ba6f86e0dbbdbbf852cb3f9d44c0ebfd408a744ac71eebcd'.

<img width="383" alt="screen shot 2018-03-07 at 11 14 15" src="https://user-images.githubusercontent.com/699063/37066261-bed9b1c0-21f8-11e8-9495-4f6164b2fc86.png">

**Comment by Bucimis** [comment]
Hi @guizmo,

`BadDeviceToken` means the app received a push token that was invalid for the credentials uploaded to the dashboard. Please verify that 1) the correct provisioning profile was installed in your app file 2) push notifications are enabled for your app id in the iOS Developer Center 3) Push Capabilities are enabled for your app in Xcode 4) the correct p8/p12 files were uploaded to the dashboard.

Thanks,
Braze SDK Engineering

**Comment by guizmo** [comment]
It is all working now... i am not sure what change fixed it but it does...

**Comment by Bucimis** [comment]
@guizmo sounds good, thanks for letting us know! closing for now

**Comment by davidciklum** [comment]
Hi @Bucimis 
I'm facing the same problem now using react-native app. Having updated SDK to `3.8.4` and `react-native-appboy-sdk` to `^1.8.1`.

Until some point Push notifications have worked. We call `changeUser(ID)` from a react-native app. Having `console.log()` in native app and checking xcode log, ID and push token have been registered:
```
[info][tid:com.facebook.react.JavaScript] User is: xxxxxxx
[info][tid:main][AppboyReactBridge.m:61] [Appboy sharedInstance] changeUser with value xxxxxxx
AppName[522:84992] [Appboy sharedInstance] changeUser with value xxxxxxx
AppName[522:84992] This is push token: <c90ddbb1 xxx xxx xxx xxx xxx xxx xxx>
```

When I try to send a message to that user, I'm getting a mentioned error message in user Push changelog:
`Received 'BadDeviceToken' sending to 'c90ddbb19ec5...`

When I create campaign, I create an iOS Push for all iOS users but filtered to that user only.

Thanks for any help!

David M.

**Comment by Bucimis** [comment]
@davidciklum thanks for getting in touch. Please make sure your app's entitlements are set up correctly and that you are pointing to the correct environment. See https://developer.apple.com/documentation/usernotifications/aps-environment?language=objc for more information.

**Comment by MauriceArikoglu** [comment]
@Bucimis how can we test push notifications in development environment? Add the user as test user or what?

**Comment by Bucimis** [comment]
Hi @MauriceArikoglu,

Thanks for getting in touch! From our docs - "You can upload either your development or production push certificates to the dashboard for your distribution provisioning profile apps, but you can only have one active at a time. As such, if you wish to do repeated testing of push notifications once your app goes live in the App Store, we recommend setting up a separate App Group or App for the development version of your app." For more, see https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/#step-1-configure-push-notifications

**Comment by shuzootani** [comment]
Hi @Bucimis 
what about android?
I got an error "DEVICE_UNREGISTERED", which I don't know how to configure on android although I followed the docs.
Thanks
