### ISSUE TITLE
AppboyReactBridge raises Appboy sharedInstance warning

### ISSUE THREAD

**Issue by guizmo** [Appboy/appboy-react-sdk#31]
in AppboyReactBridge.m, setSDKFlavor is called as soon as we import 'react-native-appboy-sdk'
(import ReactAppboy from 'react-native-appboy-sdk';)
RCT_EXPORT_METHOD(setSDKFlavor) {
  [Appboy sharedInstance].sdkFlavor = REACT;
}
At this time [Appboy startWithApiKey] has not returned yet and a warning is raised

     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **     before Appboy was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************

**Comment by Bucimis** [comment]
Hi @guizmo,

Please make sure you are calling `startWithApiKey` in your  `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` delegate method and that the SDK is being successfully initialized.

Let us know if that fixes the issue.

Thanks,
Braze SDK Engineering

**Comment by guizmo** [comment]
It is the case

**Comment by Bucimis** [comment]
Hi @guizmo,

We just released another revision 1.5.2 which should fix the issue. Our internal project setup was slightly different than yours which is why we didn't repro initially.

Let us know how it works.

Thanks & cheers,
Braze SDK Team

**Comment by Bucimis** [comment]
@guizmo closing - if you're still encountering this issue, please open a new issue. thanks!
