### ISSUE TITLE
notificationSubscriptionTypes: OPTED_IN

### ISSUE THREAD

**Issue by guizmo** [Appboy/appboy-react-sdk#32]
notificationSubscriptionTypes OPTED_IN should be "optedin" in /node_modules/react-native-appboy-sdk/index.js

ATM it is: 
  NotificationSubscriptionTypes: {
    'OPTED_IN': 'opted_in',
    'SUBSCRIBED': 'subscribed',
    'UNSUBSCRIBED': 'unsubscribed'
  },

**Comment by Bucimis** [comment]
Hi @guizmo,

Thanks for bringing this to our attention and apologies for the inconvenience. We just released v1.5.1, which fixes the issue.

Thanks,
Braze SDK Team
