### ISSUE TITLE
AppboyReactBridge.launchNewsFeed() doesn't update locale

### ISSUE THREAD

**Issue by lilyxl8** [Appboy/appboy-react-sdk#35]
Hi team,
In our app we call `Appboy.launchNewsFeed()`, which calls the same method in the SDK's [`AppboyReactBridge`](https://github.com/Appboy/appboy-react-sdk/blob/27510d78670b32ac6394a0ca65d899d5f71564d0/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m#L223). This brings up the Newsfeed in a new window in the user's app language.

After the user changes their language in Settings (both in our app and natively), the Newsfeed remains in the old language. Even after reinstalling our app, the issue persists. I suspect the view is being cached by Appboy.

Is there any way to fix this behavior? Thanks in advance!

**Comment by Bucimis** [comment]
@lilyxl8 https://www.braze.com/academy/Dashboard_Features/#sending-messages-based-on-language-most-recent-locale-and-time-zone for more

**Comment by Bucimis** [comment]
@lilyxl8 closing, please let us know if you have further questions.

**Comment by lilyxl8** [comment]
This helps, going to see if we can detect locale from our dashboard! Thanks

**Comment by lilyxl8** [comment]
Hi,
I did as you suggested and updated our locale attribute in the Braze backend, when the user changes app languages. When they open Newsfeed, it still shows the old articles. Only when they pull down to refresh, do the new articles for the correct language get loaded.
This seems like a limitation of Newsfeed, that it caches the view?
Thanks

**Comment by Bucimis** [comment]
Hi @lilyxl8, the feed is indeed cached locally, however, you can request a feed update from Braze servers manually using `requestFeedRefresh();`. I would experiment with a system where if the user has changed their locale since last opening their feed, the app requests a feed refresh the next time they open the feed.
