### ISSUE TITLE
AppboyProject fails to start

### ISSUE THREAD

**Issue by josin** [Appboy/appboy-react-sdk#37]
I was following steps to run `AppboyProject` on Android and end up with red screen on the Android device.

![screenshot_20180511-134901](https://user-images.githubusercontent.com/381741/39923062-5fd571de-5522-11e8-8c1c-2b6c88eedbad.png)

On the other side, iOS build (based on the documentation) fails to start with

```
ppboyKit.h' file not found
#import "AppboyKit.h"
        ^~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **



The following build commands failed:
	CompileC /Users/josefsin/dev/github/appboy-react-sdk/AppboyProject/ios/build/Build/Intermediates.noindex/AppboyReactBridge.build/Debug-iphonesimulator/AppboyReactBridge.build/Objects-normal/x86_64/AppboyReactBridge.o AppboyReactBridge/AppboyReactBridge.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AppboyProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AppboyProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Are there any specific requirements when running the `AppboyProject`?

**Comment by Bucimis** [comment]
Hi @josin, thanks for getting in touch!

Android:
It looks like the Braze SDK may have been added more than once. I'd try cleaning out your `node_modules` directory and running `npm_install` again, and double checking that the react-native-appboy-sdk package is only included once.

iOS:
It looks like the Braze iOS SDK's header files weren't found.  I'd make sure `pod install` successfully added our Pod to your local directory, and also make sure that `"Build Settings" --> "Header Search Paths"` in XCode contains a path that points to our header files.

**Comment by josin** [comment]
@Bucimis, thanks for your reply.

Android:
I was able to have it running and working.

iOS:
No luck here, still getting the same error. Here are some more details from my workspace if that helps you a bit.

```shell
➜  AppboyProject git:(master) ✗ find . -name "AppboyKit.h"
./ios/Pods/Appboy-iOS-SDK/AppboyKit/headers/AppboyKitLibrary/AppboyKit.h
./ios/Pods/Headers/Public/Appboy-iOS-SDK/AppboyKit.h
./ios/Pods/Headers/Private/Appboy-iOS-SDK/AppboyKit.h
```

![screen shot 2018-05-16 at 16 22 53](https://user-images.githubusercontent.com/381741/40123010-69ba9a38-5925-11e8-8289-68d43e7c47a6.png)

**Comment by Bucimis** [comment]
@josin nothing looks awry there.

On the React Native repo I see https://github.com/facebook/react-native/issues/14423 which suggests clearing your `rm ~/.rncache` and re-running `react-native run-ios`.

**Comment by josin** [comment]
@Bucimis I've tried proposed solution, but that didn't work either.

**Comment by Bucimis** [comment]
@josin could you provide us concrete steps to repro?

**Comment by josin** [comment]
@Bucimis , sure I'm doing exactly what the [README](https://github.com/Appboy/appboy-react-sdk/blob/master/README.md) says:

```shell
git clean -xfd
npm install
cd AppboyProject
npm install
cd ios
pod install
cd ..
react-native run-ios
```

**Comment by Bucimis** [comment]
Hi @josin,

Just wanted to update here. The issue is that `npm install` is symlinking to the local Braze library instead of copying it to the `node_modules` folder. As a result, the bridge iOS code in the Braze library isn't able to find the Braze native iOS library in the expected place. The best way to work around this for now is to use the remote npm package from your sample app (change https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/package.json#L11 to use `17.0.0` instead of `file:../`).

We're still working on a permanent fix and will let you know when we have one.

Cheers,
Braze SDK Eng
