### ISSUE TITLE
Need support for Facebook linking for profile

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#4]
Would love to see a bump of the SDK, and the ability to assign/associate facebook to our users.

**Comment by briancaw** [comment]
Hi @zevmo 

We're planning on releasing an updated SDK in the next few weeks, and we'll likely make this addition.  Will confirm once we've finished speccing the update.

Please let me know if you have any other comments/questions, and thanks very much for reporting this issue!

Thanks,
Brian

**Comment by tiffanylu** [comment]
Hi @zevmo,

We just released v1.0.0, which exposes `ReactAppboy.setFacebookData()` for integrating Facebook profiles with Appboy. Thanks again for raising this up!

Best,
Tiff
