### ISSUE TITLE
AppboyReactBridge.launchNewsFeed got 0 arguments, expected 1

### ISSUE THREAD

**Issue by psanowski** [Appboy/appboy-react-sdk#43]
On android when call launchNewsFeed app crashes in react java bridge
`AppboyReactBridge.launchNewsFeed got 0 arguments, expected 1`
bug introduced in appboy-react-sdk 1.7.0

**Comment by Bucimis** [comment]
@psanowski thanks for bringing this up, we're aware and will have a fix shortly

**Comment by Bucimis** [comment]
@psanowski just released a fix in 1.7..2
