### ISSUE TITLE
How to close Slide-up in-app message programatically

### ISSUE THREAD

**Issue by psanowski** [Appboy/appboy-react-sdk#46]
I have a situation when an iOS action sheet popup is displayed over an opened in-app message.
In this case focus is still on the app window and action sheet not working

Any idea how to resolve this problem?
or how to close in-app message before action popup?

**Comment by Bucimis** [comment]
Hi @psanowski,

Are you using `UIActionSheet` or  `UIAlertController` with a `preferredStyle` of `UIAlertController.Style.actionSheet`? Also, which type of in-app message are you using? I would recommend not displaying the iOS action sheet during IAM display if possible. If you implement `ABKInAppMessageUIDelegate`, you can be notified when IAMs appear and disappear.

**Comment by psanowski** [comment]
I'm using UIActionSheet and Slideup in-app message
with this message displayed my user can navigate through screens and I'm not able to disable navigation
This is why I want to discard this message

**Comment by Bucimis** [comment]
@psanowski gotcha, thanks. Currently you can accomplish that through iOS native code via `[[Appboy sharedInstance].inAppMessageController.inAppMessageUIController hideCurrentInAppMessage:YES];` (see https://appboy.github.io/appboy-ios-sdk/docs/protocol_a_b_k_in_app_message_u_i_controlling-p.html). There is not yet a javascript wrapper method for hiding the current in-app message.

**Comment by Bucimis** [comment]
@psanowski anytime, feel free to open a new issue if you run into any other blockers
