### ISSUE TITLE
Initialization SDK from react-native

### ISSUE THREAD

**Issue by davidciklum** [Appboy/appboy-react-sdk#48]
Hi Braze,
We use react-native SDK for our app. We would like to have a better control over initialization process of SDK library through react-native code.
One of case we face is to limit anonymous user creation every time use uses app. We would like to call init SDK upon some kind of event, i.e. user login together will `changeUser()` call.

**Should be possible to have an initialization method available in react-native library instead of in native code?**
If so, we would probably need to postpone a call from native code that registers a push token:
` [[Appboy sharedInstance] registerPushToken:[NSString stringWithFormat:@"%@", deviceToken]];`
save this token and send it through react-native code using `registerPushToken()` method.
Is that correct?

**Should be possible to pass some parameter to that SDK initialization method that disables creation of anonymous user, i.e. `anonymous: false`?**

Thanks!
David Mrnustik

**Comment by Bucimis** [comment]
Hi @davidciklum, thanks for getting in touch. We'll look into options for adding convenience initialization methods to our React native wrapper.

In the meantime, the best way to control initialization is the following:

On iOS
1) gate calling `startWithApiKey` and `changeUser` until the user logs in
2) if you prefer not to register your user's push token until they are logged in, you should wait to call `registerPushToken` until that point. Note that the javascript `registerPushToken()` method and the native `[Appboy registerPushToken]` method have identical functionality.

On Android
1) gate calling React native+Braze methods and all native Android methods that use the singleton (i.e. any method that calls `Appboy.getInstance`) until the user logs in.

Note that the first time your user logs in and you initialize Braze, your user will be momentarily (basically for a split second) be anonymous until you are able to call `changeUser` and identify the user for the first time.
