### ISSUE TITLE
AppboyKit.h not found

### ISSUE THREAD

**Issue by mcabs3** [Appboy/appboy-react-sdk#5]
I followed your instructions on the ReadMe and everything seems to have hooked up with rnpm, but when I run that app and do a simple changeUser I get an error on iOS

TypeError: undefined is not an object (evaluating 'AppboyReactBridge.changeUser')

From trying to link it manually, it won't build in xCode because it says that the AppboyKit.h is not found.

Maybe I am missing something, but none of your methods have been successful for me.

RN: 0.33.1
AppBoy SDK: 1.0.0
Simulator: iPhone 6

**Comment by Wenzhi** [comment]
Hey @mcabs3, 

May I ask if you integrated the Appboy IOS SDK through the Cocoapods? If you did, what version of Cocoapods you are using? Did you see any message logged in the console when you run `pod install`?

Thanks,
Wenzhi

**Comment by mcabs3** [comment]
I did not use Cocoapods, I did the manual integration due to constraints I have. I ended up getting it to work after adding the AppboyKit into the react bridge SDK and then plugged that into my application. 

The way that AppboyReactBridge.h imports AppboyKit.h would suggest that it would be in the same package, so I guess I want to ask why isn't AppboyKit included in this bridge? Or why not be rewritten to allow for the outside dependency.

**Comment by mcabs3** [comment]
this can be fixed by adding the correct header search path

**Comment by JohnRomanski** [comment]
Where is the readme for this?
I was getting the same error, but doing a `pod install` inside `AppboyProject/ios/` fixed that error.

```
/src/appboy-react-sdk/AppboyProject/node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m:4:9: fatal error: 'AppboyKit.h' file not found
#import "AppboyKit.h"
```

**Comment by tiffanylu** [comment]
Hi @JohnRomanski,

Thanks for the feedback! To make it easier for developers to get our sample app up and running, we'll be adding sample app build instructions to the README shortly. Meanwhile, instructions on integrating the Appboy SDK into a React Native application live on our documentation, which the README links out to.

Please let us know if that sounds like it would solve your issue, or if there's additional information you're looking for.

Best,
Tiff

**Comment by tiffanylu** [comment]
Hey @JohnRomanski, just a note that we've updated the README with sample app build instructions. Thanks again!

**Comment by JohnRomanski** [comment]
@tiffanylu Thanks so much! I can confirm that this works (as a non-iOS developer I was a little confounded before.)
