### ISSUE TITLE
Date as eventProperty in logCustomEvent

### ISSUE THREAD

**Issue by sergey-kozel** [Appboy/appboy-react-sdk#50]
Is there a way to add JS Date value as a parameter in logCustomEvent function?

According to [appropriate](https://github.com/Appboy/appboy-react-sdk/blob/2fd2f0f49a047d9344f82325088f6196e4723e98/index.js#L116) description it seems like there is no way to do that. But native sdk's guide says that 

> You can add metadata about custom events by passing an NSDictionary populated with NSNumber, NSString, or NSDate values.

for [IOS](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events/#tracking-custom-events) and

> Properties are defined as key-value pairs. Keys are String objects and values can be String, int, float, boolean, or Date objects.

for [Android](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/analytics/tracking_custom_events/#tracking-custom-events).

So, how was supposed to solve that part of functionality?

**Comment by Bucimis** [comment]
Hi @sergey-kozel, we don't currently support JSDate for custom event properties, however, it's on our roadmap. For the time being, we recommend using the native API or another type as a workaround.

**Comment by Bucimis** [comment]
Hi @sergey-kozel, we've added dates as a supported event and purchase property type in our latest release. For more information, see our [Changelog](https://github.com/Appboy/appboy-react-sdk/blob/master/CHANGELOG.md#added) and our [example project](https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L310)
