### ISSUE TITLE
When will react-native-appboy-sdk be upgraded to include Braze SDK v3.11.0

### ISSUE THREAD

**Issue by Martian2Lee** [Appboy/appboy-react-sdk#51]
Recently I got the following email from Braze, it asked me to upgrade Braze SDK to v3.11.0. The current `react-native-appboy-sdk` on 1.8.1 is using 3.8.4 SDK for iOS. When will `react-native-appboy-sdk` be upgraded to include 3.11.0?

We are currently on 3.8.4 SDK for iOS, need to update it to the latest Braze SDK v3.11.0.

Once we have that implemented, we should anticipate seeing a slight increase in our iOS push audiences--------------------------------------

We would like to inform you of an important issue regarding iOS push messaging given that you utilize our iOS SDK platform to send push notifications.

Issue DescriptionWe’ve identified that a small amount of your iOS users will not receive a push when both of the following occur:

Users disable Banner style notifications within the iOS system notification settings, but leave other notification styles enabled.You send an iOS push message using a Campaign or Canvas with the Push Enabled Filter set to to “true.”ImpactWe have determined that you have integrated the Braze iOS SDK and have active iOS push campaigns or Canvas messages and have used the Push Enabled filter described above in the past 30 days.

How do I resolve this issue?Please notify your iOS engineers to update to the latest Braze SDK v3.11.0.

Once your team has implemented the fix, you should anticipate seeing a slight increase in your iOS push audiences if your iOS push campaigns or Canvas workflow steps use the Push Enabled Filter.

Please contact support@braze.com or your Customer Success Manager with any questions.

**Comment by Bucimis** [comment]
@Martian2Lee we are aiming to release by mid next week

**Comment by Bucimis** [comment]
@Martian2Lee released, thank you!
