### ISSUE TITLE
lock portrait mode on launchNewsFeed method 

### ISSUE THREAD

**Issue by ishaq-aym** [Appboy/appboy-react-sdk#56]
i have to lock the orientation mode 'portrait' on default launchNewsFeed layout . but i can't find any method for that . i search and i found a solution that if i add  activity on androidManifest.xml and add property like portrait mode but the problem is that i can't find the activity name . please tell me the activity name or any method to overcome this issue . Thanks .

**Comment by Bucimis** [comment]
Hi @ishaq-aym, the fully qualified activity name is `com.appboy.ui.activities.AppboyFeedActivity"`.

The following manifest declaration should work for you:
```<activity android:name="com.appboy.ui.activities.AppboyFeedActivity" android:screenOrientation="portrait" />```
