### ISSUE TITLE
iOS deep linking not working on notification launch

### ISSUE THREAD

**Issue by simonso-nzme** [Appboy/appboy-react-sdk#60]
I am getting flaky experiences with notifications that have deep linking embed on iOS.

1) When the app is previously launched, deep linking embedded works 100% of the time

2) When the app is closed or forced closed, launching the app via a notification, deep linking works ONLY when the phone is unlocked.

I checked out the documentation and the comments on the library but failed to get a consistent result.

Believe the culprit could be **Appboy.getInitialURL((url) => { alert(url); });**

I put alerts and console logs and it seems that regardless if it is a release or debug build, the url is always null hence my handle function was never called.

I even followed the example project in this repo and the helper code provided by a Braze representative.

Any help would be appreciated.

Cheers

**Comment by simonso-nzme** [comment]
Turns out was missing the following line in the launch event of AppDelegate.m

`  
[[AppboyReactUtils sharedInstance] populateInitialUrlFromLaunchOptions:launchOptions];
`

Probably worthwhile to highlight that in the library documentation, or even under the troubleshooting section.

**Comment by Bucimis** [comment]
@simonso-nzme thanks for the feedback, you're right and we'll add documentation for `populateInitialUrlFromLaunchOptions` asap

**Comment by timmliu** [comment]
@Bucimis We ran into this as well, any update on when documentation will be added?

**Comment by mgouault** [comment]
It has been removed from the new documentation for react-native on ios, but is still used in the example :
https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/ios/BrazeProject/AppDelegate.mm#L50

I guess the documentation needs to be completed again

**Comment by esbenvb** [comment]
> Turns out was missing the following line in the launch event of AppDelegate.m
> 
> ` [[AppboyReactUtils sharedInstance] populateInitialUrlFromLaunchOptions:launchOptions];`
> 
> Probably worthwhile to highlight that in the library documentation, or even under the troubleshooting section.

Thank you!

In 2024 I still needed to do this with v8.2.0

```
#import "BrazeReactUtils.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

  [[BrazeReactUtils sharedInstance] populateInitialUrlFromLaunchOptions:launchOptions];

```
