### ISSUE TITLE
how to deep link to specific screen from a push notification.

### ISSUE THREAD

**Issue by shuzootani** [Appboy/appboy-react-sdk#61]
Hi @Bucimis 
I'd like to do deep linking to some specific screens from a push notification.
I've read the docs but I can't find any clear steps to setup deep links using for react native app.
I'm not familiar with Java and Objective-C so I'd really appreciate if you could guide me how to setup deep-linking both on android and ios.

Thanks

**Comment by Bucimis** [comment]
@shuzootani 

For Android, setting up deep links is identical to setting up deep links on native Android apps. For more information, see:
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#step-3-add-deep-links

Our Android sample app contains an e2e example: https://github.com/Appboy/appboy-ios-sdk/blob/8908d41f213de517530a943e598eee4d4360ff1d/Example/Stopwatch/Stopwatch-Info.plist#L30

On iOS, setting up deep links is also identical to setting up deep links on native iOS apps. For more information, see:
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#step-3-add-deep-links

Our iOS sample app contains an e2e example: https://github.com/Appboy/appboy-ios-sdk/blob/8908d41f213de517530a943e598eee4d4360ff1d/Example/Stopwatch/Stopwatch-Info.plist#L35

To handle deep links inside of React components, you'll need to implement RCTLinking, see https://facebook.github.io/react-native/docs/linking

On iOS, you'll additionally have to add `populateInitialUrlFromLaunchOptions` to your appdelegate's `didFinishLaunchingWithOptions` method (iOS) and `ReactAppboy.getInitialURL()` to your `componentDidMount()` method (javascript). See https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/ios/AppboyProject/AppDelegate.m#L53 and https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L78

Our AppboyProject sample app contains a complete example of this setup.

**Comment by shuzootani** [comment]
@Bucimis Hi thanks for the links,
As asked in #62, I'd like to know more about
> how do I send the event back to the react native side to handle it?

especially, deep linking to specific screen from a push notification.

I checked out the sample project in this repo, but my app has multiple screens using `react-native-navigation` for navigation so `Linking.addEventlistener('url')` and `Linking.getInitialURL` in componentDidMount doesn't really make sense, and I'm not sure how to do listening to braze deep links instead of that approach.

So I'd really appreciate if you have any ideas about it and let me know what I'm doing wrong.

Here is what I did so far for setting up deep link on android.

- added <intent-filter/> in AndroidManifest.xml following the doc
``` AndroidManifest.xml
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="${applicationId}" android:host="braze" />
</intent-filter>
```
- added `com_appboy_handle_push_deep_links_automatically` in appboy.xml
``` appboy.xml
<bool name="com_appboy_handle_push_deep_links_automatically">true</bool>
```
from dashboard, I sent a push notification with deep link option on clicking the notification.
Deeplink looks like `appName://braze/products?id=7`

please let me know if you need any further info!
Thank you

**Comment by shuzootani** [comment]
@Bucimis 
I could probably use [routeUserWithNotificationOpenedIntent](https://github.com/Appboy/appboy-android-sdk/blob/6267cccc04f5a98ced04c7fa81910bfa063df782/android-sdk-ui/src/main/java/com/appboy/push/AppboyNotificationUtils.java#L110) or [handleNotificationOpened](https://github.com/Appboy/appboy-android-sdk/blob/6267cccc04f5a98ced04c7fa81910bfa063df782/android-sdk-ui-x/src/main/java/com/appboy/uix/push/AppboyNotificationUtils.java#L37)?
I still don't get how it works about between react-native and android.

``` java
public class BrazeNotificationListener extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
      String packageName = context.getPackageName();
      String pushReceivedAction = packageName + AppboyNotificationUtils.APPBOY_NOTIFICATION_RECEIVED_SUFFIX;
      String notificationOpenedAction = packageName + AppboyNotificationUtils.APPBOY_NOTIFICATION_OPENED_SUFFIX;
      String notificationDeletedAction = packageName + AppboyNotificationUtils.APPBOY_NOTIFICATION_DELETED_SUFFIX;

      String action = intent.getAction();

      if (pushReceivedAction.equals(action)) {
         // Received push notification
      } else if (notificationOpenedAction.equals(action)) {
        AppboyNotificationUtils.routeUserWithNotificationOpenedIntent(context, intent);
       // or AppboyNotificationUtils.handleNotificationActionClicked(context, intent);
      } else if (notificationDeletedAction.equals(action)) {
        // Received push notification deleted intent
      } else {
        // Ignoring intent with unsupported action
      }
    }
}
```

``` xml
// turn this off since I use custom handler
<bool name="com_appboy_handle_push_deep_links_automatically">false</bool>
```

**Comment by Bucimis** [comment]
@shuzootani I recommend continuing to use `com_appboy_handle_push_deep_links_automatically`. For receiving the deep link in React, use RCTLinking's `getInitialURL()` method as shown in our example here https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L66

**Comment by shuzootani** [comment]
actually, I didn't need to do anything but 
``` xml 
<bool name="com_appboy_handle_push_deep_links_automatically">true</bool>
``` 
since I already had Branch setup.

Thanks and Sorry to bother you @Bucimis

**Comment by Bucimis** [comment]
@shuzootani glad to hear it was resolved & no worries at all, that's why we're here :)

**Comment by donholly** [comment]
@Bucimis I'm having the same issue here and following all of these instructions. No matter what I do, `Linking.getInitialURL` returns null when I open the app from a Braze push with a deeplink set. Any suggestions or places to look?

It seems this is how the initialURL is retrieved on Android:
https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L62

The default `AppboyNavigator` seems to handle the push deep link here:
https://github.com/Appboy/appboy-android-sdk/blob/8dbe48262d25c488e95920d73d997771e2306863/android-sdk-ui/src/main/java/com/appboy/ui/AppboyNavigator.java#L38

All I'm trying to do is get the deeplink that was sent in the push that opened the application.

My `index.js`is: 
```
class App extends PureComponent {
  async componentDidMount() {
    // Deep Link from Push
    Linking.getInitialURL()
      .then(url => {
        Alert.alert('linking', url);
      })
      .catch(err => {
        Alert.alert('linking error: ', err);
      });

    ReactAppboy.getInitialURL(url => {
      Alert.alert('appboy: ', url);
    });
    ....
}
````

`Appboy.xml`
```
<resources>
    <string translatable="false" name="com_appboy_api_key">@string/BRAZE_ANDROID_API_KEY</string>
    <string translatable="false" name="com_appboy_custom_endpoint">@string/BRAZE_CUSTOM_ENDPOINT</string>
    <string translatable="false" name="com_appboy_firebase_cloud_messaging_sender_id">@string/ANDROID_FCM_SENDER_ID</string>
    <bool name="com_appboy_firebase_cloud_messaging_registration_enabled">true</bool>
    <bool name="com_appboy_handle_push_deep_links_automatically">true</bool>
</resources>
```

`AndroidManifest.xml`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app.my">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />

    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:theme="@style/AppTheme">

        <meta-data android:name="com.bugsnag.android.API_KEY" android:value="${BUGSNAG_API_KEY}" />

        <service android:name="com.appboy.AppboyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="ourappscheme" />

                <data android:scheme="https" android:host="ourdomain.com" />
                <data android:scheme="https" android:host="ourotherdomain.com" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

    </application>

</manifest>
```

**Comment by Bucimis** [comment]
@donholly The setup more or less looks good to me. When firing the deep link through `adb` (see https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/troubleshooting/#2-verify-custom-handling-logic) does it still not work?

It may also be worth making a few sanity checks, like whether the scheme name is spelled correctly. I also don't think it should matter, but it might be worth experimenting with changing the `launchMode` to see if it works in another configuration.

**Comment by donholly** [comment]
Thanks for the quick reply, @Bucimis!

Sorry, I forgot to mention that my `adb` deep link testing does work as expected:
`db shell am start -W -a android.intent.action.VIEW -d "ourapp://location" com.ourapp.test`

We don't have any custom handling in the app, so I don't think that should be the issue. I haven't been able to trace why exactly, but it seems like the `uri` in the push notification is not getting put in the right place to get picked up by `getInitialURL`. 

I'm 100% certain the deep link is being sent the same via Braze as it is when testing with `adb`.

I've tried using different a `launchMode` (`standard` and `singleInstance`) but it doesn't seem to make a difference. 

Any suggestions on where to hunt this down?

Thanks for your help!

**Comment by donholly** [comment]
It seems like I did have one things wrong in my `AndroidManifest.xml`: I should not have multiple `android:scheme` in one `<intent-filter>`. I fixed that by breaking those into three distinct intent-filters as detailed here: https://tech.just-eat.com/2015/06/29/deep-linking-in-android-the-easy-way/

Now it seems that the `uri` I send in a push via Braze works fine if the app is already opened (this may have been the case previously), but not from a cold start. So my `getInitialURL` is still `null` when the app is cold-booted from a push notification with a deep link 😞

**Comment by Bucimis** [comment]
Hey @donholly nice catch! We can't repro getInitialURL getting a null link on cold start on our end - where is your call to `Linking.addEventListener('url', this._handleOpenUrl);`?

**Comment by donholly** [comment]
@Bucimis I noticed that using `android:launchMode="standard"` worked, but I have read that RN apps should be using `singleTask`.

I then stumbled upon https://github.com/Appboy/appboy-react-sdk/issues/62#issuecomment-507109385

It seems adding that: 
```@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    setIntent(intent);
}```

Does seem to store the initialURL and `getInitialURL` works after that. Does that help narrow down what I might be doing wrong? Or does this need to be added to the documentation?

Thanks!

**Comment by Bucimis** [comment]
@donholly that fix looks good, we've verified it on our end as well and it looks like it should have been added to documentation earlier - our apologies on that :( I'll follow up on the documentation piece but otherwise for now it looks like you should be set

**Comment by donholly** [comment]
Awesome - thanks for verifying @Bucimis!

**Comment by Minishlink** [comment]
Hi @Bucimis, looks like this important information was omitted from the new docs ;)
