### ISSUE TITLE
Android deep linking

### ISSUE THREAD

**Issue by simonso-nzme** [Appboy/appboy-react-sdk#62]
This is more or less a question rather than an issue...

I have got deep linking setup and I can confirm it is working with the following adb test command.

`$ adb shell am start -W -a android.intent.action.VIEW -d "example://gizmos" com.example.android`

The command launches the app and deep linking is working fine.

However, when I send a push notification with deep linking, my device received the notification but nothing happens when I click on it - the app does not even launch

https://www.braze.com/docs/assets/img_archive/deep_link_click_action.png?7f05e56e413bf9d0fdc4810f0948d4ca

According to the little help text in the image, I need to update my broadcast receiver in native code.

https://github.com/Appboy/appboy-android-sdk/blob/master/samples/custom-broadcast/src/main/java/com/appboy/custombroadcast/AppboyBroadcastReceiver.java

This is what I found in the Braze documentation, I can add the java file and change the AndroidManifest on the native side to support this but how do I send the event back to the react native side to handle it?

Would you be able to provide me example of how I can set this up?

P.S. when I send a push notification with the OPEN APP option, it worked fine, just not with deep linking

**Comment by Bucimis** [comment]
@simonso-nzme did you enable automatic push deep link handling in your appboy.xml? See https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#step-3-add-deep-links

You won't need to make a custom broadcast receiver to handle push deep links unless you need custom deep link handling

**Comment by simonso-nzme** [comment]
Hi,

I am currently trying to get Android working. I have encountered a similar issue I have got with iOS where initialURL was not called. Hence the app launches with push notification, but deep linking action was never called. (If the app has launched previously, it works)

To resolve the iOS issue, I needed to add the following line to AppDelegate.
`  [[AppboyReactUtils sharedInstance] populateInitialUrlFromLaunchOptions:launchOptions];
`
My question is, is there something I need to call like the above on Android to trigger initialURL?

Cheers,

**Comment by Bucimis** [comment]
@simonso-nzme 
1) Are you using the latest version of the react+braze sdk? This behavior could have occurred on older versions of the react sdk because our intents didn't always include `FLAG_ACTIVITY_NEW_TASK` - See https://github.com/Appboy/appboy-react-sdk/issues/55 for details
2) When testing with `adb shell am start`, does it work both when the app is closed and in the background?

**Comment by simonso-nzme** [comment]
Hi,

Thanks for the reply

1) I am using 1.11.1

2) adb test command for deep linking works on both scenarios

Cheers,

**Comment by simonso-nzme** [comment]
Just upgraded to the latest version

"react-native-appboy-sdk": "^1.13.0"

Same issue, works only when the app is running in the background.

I have got both

```
<bool name="com_appboy_handle_push_deep_links_automatically">true</bool>
<bool name="com_appboy_push_deep_link_back_stack_activity_enabled">true</bool>
<string name="com_appboy_push_deep_link_back_stack_activity_class_name">com.company.myapp.MainActivity</string>
```

Please advise.

**Comment by Bucimis** [comment]
@simonso-nzme I think you're affected by an issue we fixed in Braze Android SDK 3.5.0, see https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#breaking (third bullet).

If you remove the configured back stack activity, I would expect links to work normally. Could you confirm that?

If that's the case, the resolution will be for us to update the React Native SDK to use Braze Android SDK 3.5.0.

**Comment by simonso-nzme** [comment]
Hi @Bucimis 
Thanks for the quick reply.
I tried removing: 
`com_appboy_push_deep_link_back_stack_activity_enabled`
`com_appboy_push_deep_link_back_stack_activity_class_name`
from the appboy.xml

The same issue works only when the app is running in the background.

**Comment by simonso-nzme** [comment]
I've managed to set up the Sample project to link with our Braze account. Sample project works perfectly fine. Tried to compare the differences. I believe I've found the culprit.

```
android:name=".MainActivity"
android:launchMode="singleTask"
```

If I remove ```android:launchMode="singleTask"```, deep linking works.

However, I do need the singleTask to be there.

**Comment by Bucimis** [comment]
@simonso-nzme we couldn't reproduce deep linking not working for `singleTask` activities. Could you provide verbose sdk logs for the working and non-working cases?

**Comment by simonso-nzme** [comment]
Hi @Bucimis ,

I wonder if this helps.
I've created a test repo to replicate this issue.

This is based on the AppBoy sample project except I made a few changes.

[https://github.com/simonso-nzme/appboy-test-project](https://github.com/simonso-nzme/appboy-test-project)

1) I have changed the package.json 
   a) revert react-native to v0.55.4
   b) use the latest version of appboy-react-sdk (1.13.0)

2) Added the code you suggested in MainActivity.java to support `singleTask`

3) I have removed the `com_appboy_api_key` and `com_appboy_firebase_cloud_messaging_sender_id`

4) Added `com_appboy_custom_endpoint` because I have one assigned to my account

With this repo, I can replicate the following

a) having `android:launchMode="singleTask"` - failed to alert the deep link
b) removing `android:launchMode="singleTask"` - the deep link is shown in the alert 


Cheers,

**Comment by simonso-nzme** [comment]
In terms of logs, here is the filtered log from adb logcat:

my customURL is: `goapprn://`

[braze.txt](https://github.com/Appboy/appboy-react-sdk/files/3343676/braze.txt)

**Comment by simonso-nzme** [comment]
I think I have done it, it started working when I put the following override on MainActivity


    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }

**Comment by Bucimis** [comment]
Hi @simonso-nzme thanks for following up and for all this information and investigation. Glad to hear that things are working (at a high level the fix looks reasonable to me) - would you like us to take a deeper look or is this issue good to close?

**Comment by simonso-nzme** [comment]
Hi @Bucimis ,

I am just really glad it's over :D 
But I would like to know why it wasn't working for me. It would be nice info that I can pass on to the wider teams who are also implementing Braze on various projects.

I am from an iOS background so I am not too familiar with Android Intent and how they work.

I've put logs around and it seems that there was something wrong with the intent and it never hit
`
Log.i(TAG, "Deep link is " + data.toString());
`

Couldn't get that going until I put that fix in.

If you have time, it would be nice to take a deeper look.

Cheers

**Comment by Lyokone** [comment]
Hey ! Thanks for your help @simonso-nzme ! 
It should definitely be in the documentation, I've spend too much time thinking it was react-native that was wrongly setup.
