### ISSUE TITLE
1.17.0 upgrade docs`Extraneous ']' before ';'`

### ISSUE THREAD

**Issue by FrancisLeigh** [Appboy/appboy-react-sdk#66]
In XCode i am getting an `Extraneous ']' before ';'` Error for the replacement code documented in [the upgrade process to `1.17.0`](https://github.com/Appboy/appboy-react-sdk/releases/tag/1.17.0)

`[[Appboy sharedInstance] registerDeviceToken:deviceToken]];`

**Comment by Bucimis** [comment]
@FrancisLeigh thank you for the callout - this has been fixed.
