### ISSUE TITLE
Android build fails after update to 1.17.1

### ISSUE THREAD

**Issue by LaVielle** [Appboy/appboy-react-sdk#67]
My Android build is failing with this error after updating react-native-appboy-sdk from 1.14.0 to 1.17.1

I simply ran `yarn update react-native-appboy-sdk@latest`, since the Release page did not say I had to make updates to the configs in the Android folder.

I'm on react-native: 0.59.9

**The error**
```
* What went wrong:
Execution failed for task ':app:preDevDebugBuild'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.appboy:android-sdk-ui:3.7.0.
     Required by:
         project :app > project :react-native-appboy-sdk
      > Could not resolve com.appboy:android-sdk-ui:3.7.0.
         > Could not get resource 'https://jitpack.io/com/appboy/android-sdk-ui/3.7.0/android-sdk-ui-3.7.0.pom'.
            > Could not HEAD 'https://jitpack.io/com/appboy/android-sdk-ui/3.7.0/android-sdk-ui-3.7.0.pom'. Received status code 522 from server: Origin Connection Time-out
```

I don't see anything about JitPack being down. I cannot open the link in my browser, could it be that the link is dead?

Or is there something else going on, maybe some updates to make in the Android folder..?

**Comment by LaVielle** [comment]
I did some testing with different versions of react-native-appboy-sdk and the problem starts when I update from 1.15.0 to 1.16.0

The [changelog](https://github.com/Appboy/appboy-react-sdk/releases) does specify any updates I should do to my integration.

I contacted support but not so helpful... Anyone know what could be going on?

**Comment by Bucimis** [comment]
@LaVielle please make sure the top-level build.gradle file in your project contains the following:
```
// top-level build.gradle
allprojects {
  repositories {
    maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
  }
}
```
The SDK is hosted on github and should be downloading from there, not jitpack
