### ISSUE TITLE
Custom attribute with 'Date' incorrectly calculates the date/time

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#7]
We are setting the custom user attribute using the documentation:

```trackCustomAttribute(`customer_send_date`, new Date());```

in our React Native app and getting the result: 

```Jan 17, 1970 at 10:24 pm EST```

**Comment by tiffanylu** [comment]
Hi @zevmo,

Thank you for reporting this issue! Are you seeing this behavior on Android, iOS or both? Our team has recently identified an SDK bug where custom attribute `Date` objects are reported incorrectly on iOS, and we are aiming to release a fix by early next week. Would this fix solve your issue, and does this timeline work for you and your team?

Best,
Tiff

**Comment by tiffanylu** [comment]
For clarification, a bug in the `setDateCustomUserAttribute:andValue:callback:` method of our [iOS bridge](https://github.com/Appboy/appboy-react-sdk/blob/master/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m) is causing `Date` data to be misreported to Appboy on iOS. We will be releasing a fix promptly and would appreciate hearing if our fix addresses the issue you're seeing. 

Best,
Tiff

**Comment by tiffanylu** [comment]
Hi @zevmo,

We just released v.1.1.0 with the fix mentioned above. I'll be closing this issue for now; please re-open if the fix does not address your issues. Thanks again for reporting!
