### ISSUE TITLE
[1.17.x] iOS build does not compile because of undeclared ABKContentCard property

### ISSUE THREAD

**Issue by marudy** [Appboy/appboy-react-sdk#72]
Hello,

iOS build fails with

* React SDK: 1.17.x
* React-Native: 0.59.8

Error is shown below:

```
node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m:374:49: property 'clicked' not found on object of type 'ABKContentCard *'

  formattedContentCardData[@"clicked"] = @(card.clicked);
```

Essentialy the complain is about this line 
`formattedContentCardData[@"clicked"] = @(card.clicked);`
in file `AppboyReactBridge.m`

Thanks

**Comment by Bucimis** [comment]
@marudy what version of the Braze iOS SDK are you using? `clicked` was added as a public property of `ABKContentCard` in version 3.10.0 https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3100

**Comment by marudy** [comment]
@Bucimis thanks for the quick response. Your feedback looks right, I was working with Braze iOS SDK version 3.8.4 even though I had upgraded this package to 1.17.2. Closing this,
