### ISSUE TITLE
[1.17.x] iOS build does not compile due to import <FLAnimatedImage/FLAnimatedImageView.h> not found

### ISSUE THREAD

**Issue by marudy** [Appboy/appboy-react-sdk#73]
![Screenshot 2019-09-20 at 15 59 17](https://user-images.githubusercontent.com/16783589/65330247-d4b0b680-dbc2-11e9-929c-da983c111cbf.png)

Tried some possible workarounds like upgrading iOS SDK etc but they didn't work for me. `<FLAnimatedImage/FLAnimatedImageView.h>` is being imported in file `ABKBaseContentCardCell.h` but does not exist as part of Appboy-iOS-SDK. What I did as a workaround is moved the missing file inside Appboy-iOS-SDK as shown below and the build compiled. Of course it's not a permanent workaround.

![Screenshot 2019-09-20 at 16 31 47](https://user-images.githubusercontent.com/16783589/65330825-27d73900-dbc4-11e9-8f11-b1b1435c5ec0.png)

**Comment by Bucimis** [comment]
@marudy closing as this issue is related to https://github.com/Appboy/appboy-react-sdk/issues/72#issuecomment-533914754.

**Comment by marudy** [comment]
Yeah seems legit @Bucimis
