### ISSUE TITLE
In App Message not appearing

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Appboy/appboy-react-sdk#76]
Hi! we've configured Braze SDK on Android
When we try to send a In App Message test message for a specific user (our test user), it says:
```
Warning: None of the selected users have matching push tokens for In-App Message.
```
What else should I do to configure this? This user has already accepted to receive push notifications

**Comment by Bucimis** [comment]
@rafaelcorreiapoli our test in-app message feature requires push notifications to be integrated and for a valid push token to belong to the user being sent the test. Can you check the user profile in question and ensure that a valid push token belongs to it?

You may also test a campaign without push by narrowing the segment/filter criteria to just your test user and sending it as normal (to that user only).

**Comment by rafaelcorreiapoli** [comment]
Hi! Thanks for the quick response
This is the push configuration for this particular user:
<img width="513" alt="Screen Shot 2019-10-21 at 18 43 10" src="https://user-images.githubusercontent.com/12840136/67245578-b1cc2900-f432-11e9-9fa6-2eb74abad2d5.png">

**Comment by rafaelcorreiapoli** [comment]
BTW, this is our `MainApplication.java`
```
@Override
  public void onCreate() {
    super.onCreate();
    registerActivityLifecycleCallbacks(new AppboyLifecycleCallbackListener(true, true));
    AppboyLogger.setLogLevel(Log.VERBOSE);
    SoLoader.init(this, /* native exopackage */ false);
  }
```

**Comment by Bucimis** [comment]
@rafaelcorreiapoli the code looks good. It appears the token has moved to another user. Are you sure you're searching for the current user on the device?

**Comment by rafaelcorreiapoli** [comment]
Yep, I'm explicitly calling `changeUser` and `setEmail`on my code for debugging purposes
I've changed the user and email on this device several times (for debugging purposes). Can this be affecting the usage of push notifications and in app messaging?

**Comment by rafaelcorreiapoli** [comment]
Ok so I've found out what was wrong:
I had forgotten to add the firebase keys to our staging app, so it was not sending pushes properly
But the error shown in the UI led me to think the error was with the push token registration

**Comment by Bucimis** [comment]
@rafaelcorreiapoli thanks for following up - I'll pass this feedback along to our product team. Glad things are working & let us know if anything else comes up
