### ISSUE TITLE
Ability to have custom styling

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#8]
We would love the ability to add custom styling to the News Feed.

**Comment by tiffanylu** [comment]
Hi @zevmo, thanks for surfacing! 

Our native iOS and Android platforms offer News Feed customization options that should apply to React Native as well. You can see our iOS Feed customization documentation [here](https://www.appboy.com/documentation/iOS/#theming-the-news-feed), and our Android docs [here](https://www.appboy.com/documentation/Android#news-feed-customization). 

We would love to hear more about what particular methods of customization you're looking for, which would help guide our investigation into adding a Feed customization solution for React Native.

Best,
Tiff

**Comment by zevmo** [comment]
@tiffanylu We would love to have the ability to add the news feed into the view, rather than a pop component (over the rest of the screen like a modal).

Other than that, the ability to customize the header / link colors, and main background color would really be a big help.

**Comment by tiffanylu** [comment]
Hi @zevmo,

We've previously investigated exposing our News Feed as an embeddable UI component, but React Native does not currently support bridging native view controllers—see https://github.com/Appboy/appboy-react-sdk/issues/2 for more context. We will continue investigating other methods of exposing our Feed as React Native continues to mature. Your feedback on our product is much appreciated, and we will also be looking into a custom styling solution for React Native. 

In the meantime, we currently expose this latter functionality through native integration points. The NUI framework allows you to customize the News Feed on iOS using style sheets similar to CSS: you can see our documentation [here](https://www.appboy.com/documentation/iOS/#theming-the-news-feed) and a sample stylesheet [here](https://github.com/Appboy/appboy-ios-sdk/blob/master/Example/StopwatchNUIStyle.nss). On Android, you can customize the Feed by overriding values in your application's `styles.xml`: see our documentation [here](https://www.appboy.com/documentation/Android#overriding-styles) and a list of themable elements in our sample `styles.xml` [here](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/res/values/styles.xml#L378). If your need is urgent or your timeline less flexible, these options are supported on our native platforms and should work for your application.

Best,
Tiff
