### ISSUE TITLE
Question: Any side effect to call enableSDK() and disableSDK() multiple times

### ISSUE THREAD

**Issue by DeshmukP** [Appboy/appboy-react-sdk#84]
HI,

On both IOS and Android, Any side effect if I call  enableSDK() and disableSDK() on each if API response is true/false?

**Comment by Bucimis** [comment]
@DeshmukP what is your usecase? You can call each method multiple times, but note that the resulting behavior will be slightly different on Android vs iOS. See https://github.com/Appboy/appboy-react-sdk/blob/bcac45d33d2d41dd6c3c227f2719e10430a8851a/CHANGELOG.md#added-11 for more
