### ISSUE TITLE
React Native 0.40 compatibility

### ISSUE THREAD

**Issue by MOM** [Appboy/appboy-react-sdk#9]
Is there a timeline for Appboy's SDK to become 0.40 compatable?

**Comment by zevmo** [comment]
+1

**Comment by tiffanylu** [comment]
Hi @MOM,

We're aiming to release with RN 0.40 compatibility by the end of next week. Please let us know if that timeline works for you.

Best,
Tiff

**Comment by MOM** [comment]
Great, thank you

**Comment by artkow** [comment]
+1

**Comment by zevmo** [comment]
ASAP due to other components having breaking changes / bug updates compatibility. Thanks!

**Comment by tiffanylu** [comment]
Hi @MOM and @zevmo,

Due to the official release of React Native v0.41.0 yesterday, we will be moving our release to early next week to ensure fully up-to-date compatibility. Thank you all for your patience!

Best,
Tiff

**Comment by tiffanylu** [comment]
Hi all,

We just released version 1.2.0 of our React Native bridge, which is compatible with RN v.0.41.0. Thanks for opening this issue!

Best,
Tiff
