### ISSUE TITLE
logCustomEvent is not logging on event on dashboard

### ISSUE THREAD

**Issue by TimothyJAveni** [Appboy/appboy-react-sdk#90]
when i call `logCustomEvent` then open dashboard-> User Search
there is not logged any event on my user detail 
```
ReactAppboy.logCustomEvent("Search",{
    Searchdate:new Date(),
    ...searchEventData
  })
```

**Comment by Bucimis** [comment]
Hi @TimothyJAveni, the SDK periodically flushes data from time to time, typically around every 10 seconds in a standard SDK configuration with a decent network connection. If you want to force data to be flushed immediately, you can call `requestImmediateDataFlush` after logging the custom event.

I would also look at the device logs (Xcode logs or Logcat) for more details on what might be going wrong.

Note that if you don't see *any* data from the user on the dashboard, it's possible your API key or cluster is misconfigured.

**Comment by TimothyJAveni** [comment]
@Bucimis i am not getting any log in (Xcode logs or Logcat) related appboy and i have tried `requestImmediateDataFlush` and it is also not working. 

same API key is working on native android and native ios but not work in react native

**Comment by Bucimis** [comment]
@TimothyJAveni have you tried enabling verbose logging? The instructions for React Native are the same as on native. See https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/#braze-log-level and https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#braze-log-level

**Comment by TimothyJAveni** [comment]
@Bucimis `AppboyLogger.setLogLevel(Log.VERBOSE);` how can use this in react native android and after add this into info.plist
```

<key>Appboy</key>
<dict>
	<key>LogLevel</key>
	<string>0</string>
</dict>
```
i am unable to get any log in (Xcode logs or Logcat)

**Comment by TimothyJAveni** [comment]
@Bucimis are you there?

**Comment by Bucimis** [comment]
@TimothyJAveni Does `ReactAppboy.logCustomEvent("Search")` work? Do things only break after adding properties?

**Comment by TimothyJAveni** [comment]
@Bucimis it is also not working. when i register user it is register user on braze dashboard perfectly but not logging custom event

**Comment by nomi9995** [comment]
@Bucimis same problem

**Comment by wesleyorbin** [comment]
@TimothyJAveni @nomi9995 We are unable to reproduce this issue on our side. To help us investigate, can you provide us with the SDK and OS versions that you are experiencing this issue with? Any other code snippets you could provide (e.g., how the SDK is imported/required) would also be helpful.

**Comment by TimothyJAveni** [comment]
@Bucimis @wesleyorbin  i am getting this error on logcat

```
 ******************************************************************
 **                        !! WARNING !!                         **
 **  The current API key/endpoint combination is invalid. This   **
 ** is potentially an integration error. Please ensure that your **
 **     API key AND custom endpoint information are correct.     **
 >> API key    : XXXXXXXXXXXXXX
 >> Request Uri: https://sondheim.appboy.com/api/v3/data
 ******************************************************************
```

**Comment by nomi9995** [comment]
@TimothyJAveni you are using example
remove this from info.plist for ios
```
<key>Endpoint</key>
<string>sondheim.appboy.com</string>
```
remove this from appboy.xml
```
<string translatable="false" name="com_appboy_server_target">STAGING</string>
```
it will resolve your problem

**Comment by nomi9995** [comment]
@Bucimis @wesleyorbin  i am using this in `info.plist` 
```
<key>Appboy</key>
<dict>
	<key>LogLevel</key>
	<string>0</string>
</dict>
```

but logs are working in example project from this sdk but not working from my project. any idea?

**Comment by Bucimis** [comment]
@nomi9995 are other settings from that `info.plist` being reflected in the final app build? Are there other conflicting plist entries that might be overriding it?

**Comment by nomi9995** [comment]
@Bucimis this is my `info.plist` 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Appboy</key>
    <dict>
        <key>LogLevel</key>
        <string>0</string>
    </dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Chalhoub</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>com.theentertainerme.chb.ent</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Chalhoub</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>chalhoubentertainer</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleURLName</key>
			<string>OAuthRedirect</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.theentertainerme.chb.ent</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>0.0.1</string>
	<key>Fabric</key>
	<dict>
		<key>APIKey</key>
		<string>xxxx</string>
		<key>Kits</key>
		<array>
			<dict>
				<key>KitInfo</key>
				<dict/>
				<key>KitName</key>
				<string>Crashlytics</string>
			</dict>
		</array>
	</dict>
	<key>FacebookAdvertiserIDCollectionEnabled</key>
	<false/>
	<key>FacebookAutoInitEnabled</key>
	<false/>
	<key>FacebookAutoLogAppEventsEnabled</key>
	<false/>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-3940256099942544~1458002511</string>
	<key>GADDelayAppMeasurementInit</key>
	<true/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSCalendarsUsageDescription</key>
	<string>Allow Chalhoub to access your calendar</string>
	<key>NSCameraUsageDescription</key>
	<string>Allow Chalhoub to use your camera</string>
	<key>NSContactsUsageDescription</key>
	<string>Allow Chalhoub to access your contacts</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Allow Chalhoub to use your location</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Allow Chalhoub to access your microphone</string>
	<key>NSMotionUsageDescription</key>
	<string>Allow Chalhoub to access your device's accelerometer</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Give Chalhoub permission to save photos</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Give Chalhoub permission to access your photos</string>
	<key>NSRemindersUsageDescription</key>
	<string>Allow Chalhoub to access your reminders</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array/>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDefault</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>branch_key</key>
	<dict>
		<key>live</key>
		<string>xxxx</string>
	</dict>
</dict>
</plist>

```

I think there is no another key is conflicting

**Comment by nomi9995** [comment]
i have fixed logs by remove disable against `OS_ACTIVITY_MODE` (Product -> Scheme -> Edit Scheme -> Run -> Arguments -> Environment)
