### ISSUE TITLE
ReactAppboy.setIntCustomUserAttribute is not a function 

### ISSUE THREAD

**Issue by Diego-F-Aguirre** [Appboy/appboy-react-sdk#92]
Affects: iOS & Android

### Problem
The following fuctions:
```
            ReactAppboy.setIntCustomUserAttribute('user_company_id', state.app.me.company?.id);
            ReactAppboy.setStringCustomUserAttribute('user_company_name', state.app.me.company?.name);
```
Returns the `is not a function` error.

### Environment
    "react-native-appboy-sdk": "1.19.0",
    "react-native": "0.61.5"

### Resources
- https://github.com/Appboy/appboy-react-sdk/blob/04c1404e122c16e297654f875802a9c0c7976469/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m

**Comment by wesleyorbin** [comment]
Hi @Diego-F-Aguirre! Thanks for reaching out. You should use the [`ReactAppboy.setCustomUserAttribute`](https://github.com/Appboy/appboy-react-sdk/blob/master/index.js#L216) method for both of these and it will do the type inference for you so that the correct bridge method is called.

**Comment by Diego-F-Aguirre** [comment]
Thanks so much @wesleyorbin that did the trick! I appreciate the quick response, closing this ticket.
