### ISSUE TITLE
Use the latest version of appboy-ios-sdk (v3.28.0)

### ISSUE THREAD

**Issue by altayaydemir** [Appboy/appboy-react-sdk#94]
Hello there 👋 

We'd like to bump our `appboy-react-sdk` version, but we're waiting for the  `appboy-ios-sdk` v3.28.0 bump since it includes those changes: https://github.com/Appboy/appboy-ios-sdk/issues/249

Do you have any plans to bump it soon?

Thanks!

**Comment by wesleyorbin** [comment]
Hi @altayaydemir! Thanks for reaching out. We just released version 1.24.0, which uses iOS SDK 3.28.0 (as well as Android SDK 10.1.0).
