### ISSUE TITLE
ReactAppboy.disableSDK then ReactAppboy.getInstallTrackingId crashes on iOS

### ISSUE THREAD

**Issue by philip-bui** [Appboy/appboy-react-sdk#97]
Hey guys,

Due to one of our use cases, we are disabling Braze SDK and enabling them at certain points. When we call `ReactAppboy.getInstallTrackingId` after we disabled the SDK, it crashes in iOS. 

Another scenario is if we call `ReactAppboy.disableSDK` then `ReactAppboy.enableSDK` then `ReactAppboy.getInstallTrackingId` it still crashes.

Another scenario is if we call `ReactAppboy.disableSDK`, close and open the app, and call `ReactAppboy.getInstallTrackingId` it crashes.

**React-Native Version**: 0.62.2
**Version**: 1.20.0 AND 1.25.0 (latest)

**Steps to replicate**
1. Call `ReactAppboy.disableSDK`
2. Call `ReactAppboy.getInstallTrackingId`
3. Results in Crash in iOS.
4. Results in Null Error and Empty String in Callback for Android.

**Expected:**
1. Results in Error Object in Callback.

![image (1)](https://user-images.githubusercontent.com/20367777/100401700-58f7a700-30ae-11eb-849c-7fc9ad4ec64a.png)

**Comment by Bucimis** [comment]
Closed in error - this will be fixed in our next release.
